// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/lolibrary/lolibrary/service.brand/proto/brand.proto

package brandproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/lolibrary/lolibrary/cmd/protoc-gen-router/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Brand struct {
	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Slug        string `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	ShortName   string `protobuf:"bytes,3,opt,name=short_name,json=shortName,proto3" json:"short_name,omitempty"`
	Name        string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	ImageId     string `protobuf:"bytes,6,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	// timestamps
	CreatedAt            string   `protobuf:"bytes,100,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,101,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Brand) Reset()         { *m = Brand{} }
func (m *Brand) String() string { return proto.CompactTextString(m) }
func (*Brand) ProtoMessage()    {}
func (*Brand) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee3340ccb2108214, []int{0}
}

func (m *Brand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Brand.Unmarshal(m, b)
}
func (m *Brand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Brand.Marshal(b, m, deterministic)
}
func (m *Brand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Brand.Merge(m, src)
}
func (m *Brand) XXX_Size() int {
	return xxx_messageInfo_Brand.Size(m)
}
func (m *Brand) XXX_DiscardUnknown() {
	xxx_messageInfo_Brand.DiscardUnknown(m)
}

var xxx_messageInfo_Brand proto.InternalMessageInfo

func (m *Brand) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Brand) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *Brand) GetShortName() string {
	if m != nil {
		return m.ShortName
	}
	return ""
}

func (m *Brand) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Brand) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Brand) GetImageId() string {
	if m != nil {
		return m.ImageId
	}
	return ""
}

func (m *Brand) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Brand) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type GETReadBrandRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Slug                 string   `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	ShortName            string   `protobuf:"bytes,3,opt,name=short_name,json=shortName,proto3" json:"short_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GETReadBrandRequest) Reset()         { *m = GETReadBrandRequest{} }
func (m *GETReadBrandRequest) String() string { return proto.CompactTextString(m) }
func (*GETReadBrandRequest) ProtoMessage()    {}
func (*GETReadBrandRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee3340ccb2108214, []int{1}
}

func (m *GETReadBrandRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GETReadBrandRequest.Unmarshal(m, b)
}
func (m *GETReadBrandRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GETReadBrandRequest.Marshal(b, m, deterministic)
}
func (m *GETReadBrandRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GETReadBrandRequest.Merge(m, src)
}
func (m *GETReadBrandRequest) XXX_Size() int {
	return xxx_messageInfo_GETReadBrandRequest.Size(m)
}
func (m *GETReadBrandRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GETReadBrandRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GETReadBrandRequest proto.InternalMessageInfo

func (m *GETReadBrandRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GETReadBrandRequest) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *GETReadBrandRequest) GetShortName() string {
	if m != nil {
		return m.ShortName
	}
	return ""
}

type GETReadBrandResponse struct {
	Brand                *Brand   `protobuf:"bytes,1,opt,name=brand,proto3" json:"brand,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GETReadBrandResponse) Reset()         { *m = GETReadBrandResponse{} }
func (m *GETReadBrandResponse) String() string { return proto.CompactTextString(m) }
func (*GETReadBrandResponse) ProtoMessage()    {}
func (*GETReadBrandResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee3340ccb2108214, []int{2}
}

func (m *GETReadBrandResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GETReadBrandResponse.Unmarshal(m, b)
}
func (m *GETReadBrandResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GETReadBrandResponse.Marshal(b, m, deterministic)
}
func (m *GETReadBrandResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GETReadBrandResponse.Merge(m, src)
}
func (m *GETReadBrandResponse) XXX_Size() int {
	return xxx_messageInfo_GETReadBrandResponse.Size(m)
}
func (m *GETReadBrandResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GETReadBrandResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GETReadBrandResponse proto.InternalMessageInfo

func (m *GETReadBrandResponse) GetBrand() *Brand {
	if m != nil {
		return m.Brand
	}
	return nil
}

type GETListBrandsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GETListBrandsRequest) Reset()         { *m = GETListBrandsRequest{} }
func (m *GETListBrandsRequest) String() string { return proto.CompactTextString(m) }
func (*GETListBrandsRequest) ProtoMessage()    {}
func (*GETListBrandsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee3340ccb2108214, []int{3}
}

func (m *GETListBrandsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GETListBrandsRequest.Unmarshal(m, b)
}
func (m *GETListBrandsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GETListBrandsRequest.Marshal(b, m, deterministic)
}
func (m *GETListBrandsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GETListBrandsRequest.Merge(m, src)
}
func (m *GETListBrandsRequest) XXX_Size() int {
	return xxx_messageInfo_GETListBrandsRequest.Size(m)
}
func (m *GETListBrandsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GETListBrandsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GETListBrandsRequest proto.InternalMessageInfo

type GETListBrandsResponse struct {
	Brands               []*Brand `protobuf:"bytes,1,rep,name=brands,proto3" json:"brands,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GETListBrandsResponse) Reset()         { *m = GETListBrandsResponse{} }
func (m *GETListBrandsResponse) String() string { return proto.CompactTextString(m) }
func (*GETListBrandsResponse) ProtoMessage()    {}
func (*GETListBrandsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee3340ccb2108214, []int{4}
}

func (m *GETListBrandsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GETListBrandsResponse.Unmarshal(m, b)
}
func (m *GETListBrandsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GETListBrandsResponse.Marshal(b, m, deterministic)
}
func (m *GETListBrandsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GETListBrandsResponse.Merge(m, src)
}
func (m *GETListBrandsResponse) XXX_Size() int {
	return xxx_messageInfo_GETListBrandsResponse.Size(m)
}
func (m *GETListBrandsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GETListBrandsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GETListBrandsResponse proto.InternalMessageInfo

func (m *GETListBrandsResponse) GetBrands() []*Brand {
	if m != nil {
		return m.Brands
	}
	return nil
}

type POSTCreateBrandRequest struct {
	Slug                 string   `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	ShortName            string   `protobuf:"bytes,2,opt,name=short_name,json=shortName,proto3" json:"short_name,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	ImageId              string   `protobuf:"bytes,5,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	AllowId              bool     `protobuf:"varint,10,opt,name=allow_id,json=allowId,proto3" json:"allow_id,omitempty"`
	Id                   string   `protobuf:"bytes,11,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *POSTCreateBrandRequest) Reset()         { *m = POSTCreateBrandRequest{} }
func (m *POSTCreateBrandRequest) String() string { return proto.CompactTextString(m) }
func (*POSTCreateBrandRequest) ProtoMessage()    {}
func (*POSTCreateBrandRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee3340ccb2108214, []int{5}
}

func (m *POSTCreateBrandRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_POSTCreateBrandRequest.Unmarshal(m, b)
}
func (m *POSTCreateBrandRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_POSTCreateBrandRequest.Marshal(b, m, deterministic)
}
func (m *POSTCreateBrandRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_POSTCreateBrandRequest.Merge(m, src)
}
func (m *POSTCreateBrandRequest) XXX_Size() int {
	return xxx_messageInfo_POSTCreateBrandRequest.Size(m)
}
func (m *POSTCreateBrandRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_POSTCreateBrandRequest.DiscardUnknown(m)
}

var xxx_messageInfo_POSTCreateBrandRequest proto.InternalMessageInfo

func (m *POSTCreateBrandRequest) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *POSTCreateBrandRequest) GetShortName() string {
	if m != nil {
		return m.ShortName
	}
	return ""
}

func (m *POSTCreateBrandRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *POSTCreateBrandRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *POSTCreateBrandRequest) GetImageId() string {
	if m != nil {
		return m.ImageId
	}
	return ""
}

func (m *POSTCreateBrandRequest) GetAllowId() bool {
	if m != nil {
		return m.AllowId
	}
	return false
}

func (m *POSTCreateBrandRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type POSTCreateBrandResponse struct {
	Brand                *Brand   `protobuf:"bytes,1,opt,name=brand,proto3" json:"brand,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *POSTCreateBrandResponse) Reset()         { *m = POSTCreateBrandResponse{} }
func (m *POSTCreateBrandResponse) String() string { return proto.CompactTextString(m) }
func (*POSTCreateBrandResponse) ProtoMessage()    {}
func (*POSTCreateBrandResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee3340ccb2108214, []int{6}
}

func (m *POSTCreateBrandResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_POSTCreateBrandResponse.Unmarshal(m, b)
}
func (m *POSTCreateBrandResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_POSTCreateBrandResponse.Marshal(b, m, deterministic)
}
func (m *POSTCreateBrandResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_POSTCreateBrandResponse.Merge(m, src)
}
func (m *POSTCreateBrandResponse) XXX_Size() int {
	return xxx_messageInfo_POSTCreateBrandResponse.Size(m)
}
func (m *POSTCreateBrandResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_POSTCreateBrandResponse.DiscardUnknown(m)
}

var xxx_messageInfo_POSTCreateBrandResponse proto.InternalMessageInfo

func (m *POSTCreateBrandResponse) GetBrand() *Brand {
	if m != nil {
		return m.Brand
	}
	return nil
}

type PUTUpdateBrandRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ImageId              string   `protobuf:"bytes,4,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PUTUpdateBrandRequest) Reset()         { *m = PUTUpdateBrandRequest{} }
func (m *PUTUpdateBrandRequest) String() string { return proto.CompactTextString(m) }
func (*PUTUpdateBrandRequest) ProtoMessage()    {}
func (*PUTUpdateBrandRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee3340ccb2108214, []int{7}
}

func (m *PUTUpdateBrandRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PUTUpdateBrandRequest.Unmarshal(m, b)
}
func (m *PUTUpdateBrandRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PUTUpdateBrandRequest.Marshal(b, m, deterministic)
}
func (m *PUTUpdateBrandRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PUTUpdateBrandRequest.Merge(m, src)
}
func (m *PUTUpdateBrandRequest) XXX_Size() int {
	return xxx_messageInfo_PUTUpdateBrandRequest.Size(m)
}
func (m *PUTUpdateBrandRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PUTUpdateBrandRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PUTUpdateBrandRequest proto.InternalMessageInfo

func (m *PUTUpdateBrandRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PUTUpdateBrandRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PUTUpdateBrandRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *PUTUpdateBrandRequest) GetImageId() string {
	if m != nil {
		return m.ImageId
	}
	return ""
}

type PUTUpdateBrandResponse struct {
	Brand                *Brand   `protobuf:"bytes,1,opt,name=brand,proto3" json:"brand,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PUTUpdateBrandResponse) Reset()         { *m = PUTUpdateBrandResponse{} }
func (m *PUTUpdateBrandResponse) String() string { return proto.CompactTextString(m) }
func (*PUTUpdateBrandResponse) ProtoMessage()    {}
func (*PUTUpdateBrandResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee3340ccb2108214, []int{8}
}

func (m *PUTUpdateBrandResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PUTUpdateBrandResponse.Unmarshal(m, b)
}
func (m *PUTUpdateBrandResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PUTUpdateBrandResponse.Marshal(b, m, deterministic)
}
func (m *PUTUpdateBrandResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PUTUpdateBrandResponse.Merge(m, src)
}
func (m *PUTUpdateBrandResponse) XXX_Size() int {
	return xxx_messageInfo_PUTUpdateBrandResponse.Size(m)
}
func (m *PUTUpdateBrandResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PUTUpdateBrandResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PUTUpdateBrandResponse proto.InternalMessageInfo

func (m *PUTUpdateBrandResponse) GetBrand() *Brand {
	if m != nil {
		return m.Brand
	}
	return nil
}

type DELETERemoveBrandRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DELETERemoveBrandRequest) Reset()         { *m = DELETERemoveBrandRequest{} }
func (m *DELETERemoveBrandRequest) String() string { return proto.CompactTextString(m) }
func (*DELETERemoveBrandRequest) ProtoMessage()    {}
func (*DELETERemoveBrandRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee3340ccb2108214, []int{9}
}

func (m *DELETERemoveBrandRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DELETERemoveBrandRequest.Unmarshal(m, b)
}
func (m *DELETERemoveBrandRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DELETERemoveBrandRequest.Marshal(b, m, deterministic)
}
func (m *DELETERemoveBrandRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DELETERemoveBrandRequest.Merge(m, src)
}
func (m *DELETERemoveBrandRequest) XXX_Size() int {
	return xxx_messageInfo_DELETERemoveBrandRequest.Size(m)
}
func (m *DELETERemoveBrandRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DELETERemoveBrandRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DELETERemoveBrandRequest proto.InternalMessageInfo

func (m *DELETERemoveBrandRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DELETERemoveBrandResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DELETERemoveBrandResponse) Reset()         { *m = DELETERemoveBrandResponse{} }
func (m *DELETERemoveBrandResponse) String() string { return proto.CompactTextString(m) }
func (*DELETERemoveBrandResponse) ProtoMessage()    {}
func (*DELETERemoveBrandResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee3340ccb2108214, []int{10}
}

func (m *DELETERemoveBrandResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DELETERemoveBrandResponse.Unmarshal(m, b)
}
func (m *DELETERemoveBrandResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DELETERemoveBrandResponse.Marshal(b, m, deterministic)
}
func (m *DELETERemoveBrandResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DELETERemoveBrandResponse.Merge(m, src)
}
func (m *DELETERemoveBrandResponse) XXX_Size() int {
	return xxx_messageInfo_DELETERemoveBrandResponse.Size(m)
}
func (m *DELETERemoveBrandResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DELETERemoveBrandResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DELETERemoveBrandResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Brand)(nil), "brandproto.Brand")
	proto.RegisterType((*GETReadBrandRequest)(nil), "brandproto.GETReadBrandRequest")
	proto.RegisterType((*GETReadBrandResponse)(nil), "brandproto.GETReadBrandResponse")
	proto.RegisterType((*GETListBrandsRequest)(nil), "brandproto.GETListBrandsRequest")
	proto.RegisterType((*GETListBrandsResponse)(nil), "brandproto.GETListBrandsResponse")
	proto.RegisterType((*POSTCreateBrandRequest)(nil), "brandproto.POSTCreateBrandRequest")
	proto.RegisterType((*POSTCreateBrandResponse)(nil), "brandproto.POSTCreateBrandResponse")
	proto.RegisterType((*PUTUpdateBrandRequest)(nil), "brandproto.PUTUpdateBrandRequest")
	proto.RegisterType((*PUTUpdateBrandResponse)(nil), "brandproto.PUTUpdateBrandResponse")
	proto.RegisterType((*DELETERemoveBrandRequest)(nil), "brandproto.DELETERemoveBrandRequest")
	proto.RegisterType((*DELETERemoveBrandResponse)(nil), "brandproto.DELETERemoveBrandResponse")
}

func init() {
	proto.RegisterFile("github.com/lolibrary/lolibrary/service.brand/proto/brand.proto", fileDescriptor_ee3340ccb2108214)
}

var fileDescriptor_ee3340ccb2108214 = []byte{
	// 596 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xdd, 0x6e, 0xd3, 0x30,
	0x14, 0x56, 0xfa, 0xb3, 0xae, 0x27, 0x1a, 0x08, 0xc3, 0x46, 0x1a, 0x54, 0xd1, 0x05, 0x10, 0x03,
	0xa9, 0xad, 0x34, 0xee, 0x41, 0x2d, 0xab, 0xa6, 0x49, 0x13, 0x4c, 0xa5, 0x93, 0x90, 0x90, 0xa8,
	0xd2, 0xd8, 0xea, 0x2c, 0x25, 0x4d, 0xb1, 0xdd, 0x01, 0xb7, 0x7d, 0x0f, 0x6e, 0xf7, 0x06, 0x7b,
	0x06, 0x9e, 0x81, 0xb7, 0x41, 0x39, 0x4e, 0x59, 0x92, 0xa5, 0xa9, 0x26, 0x71, 0x77, 0x7c, 0xce,
	0xf1, 0xf7, 0xf9, 0xf3, 0x77, 0x9c, 0xc0, 0xdb, 0x29, 0x57, 0x17, 0x8b, 0x49, 0xc7, 0x0b, 0x83,
	0xae, 0x1f, 0xfa, 0x7c, 0x22, 0x5c, 0xf1, 0x33, 0x11, 0x49, 0x26, 0x2e, 0xb9, 0xc7, 0x3a, 0x13,
	0xe1, 0xce, 0x68, 0x77, 0x2e, 0x42, 0x15, 0x76, 0x31, 0xee, 0x60, 0x4c, 0x00, 0x17, 0x18, 0xdb,
	0xc7, 0x1b, 0xb0, 0xbc, 0x20, 0x46, 0xf0, 0xda, 0x53, 0x36, 0x6b, 0x8b, 0x70, 0xa1, 0x98, 0x88,
	0x31, 0xf5, 0x42, 0x83, 0x3a, 0x7f, 0x0c, 0xa8, 0xf6, 0x23, 0x5c, 0x72, 0x0f, 0x4a, 0x9c, 0x5a,
	0x46, 0xcb, 0x38, 0xa8, 0x0f, 0x4b, 0x9c, 0x12, 0x02, 0x15, 0xe9, 0x2f, 0xa6, 0x56, 0x09, 0x33,
	0x18, 0x93, 0x26, 0x80, 0xbc, 0x08, 0x85, 0x1a, 0xcf, 0xdc, 0x80, 0x59, 0x65, 0xac, 0xd4, 0x31,
	0xf3, 0xc1, 0x0d, 0x58, 0xb4, 0x05, 0x0b, 0x15, 0xbd, 0x25, 0x8a, 0x49, 0x0b, 0x4c, 0xca, 0xa4,
	0x27, 0xf8, 0x5c, 0xf1, 0x70, 0x66, 0x55, 0xb1, 0x94, 0x4c, 0x91, 0x06, 0x6c, 0xf3, 0xc0, 0x9d,
	0xb2, 0x31, 0xa7, 0xd6, 0x16, 0x96, 0x6b, 0xb8, 0x3e, 0xa1, 0x11, 0x9f, 0x27, 0x98, 0xab, 0x18,
	0x1d, 0xbb, 0xca, 0xa2, 0x9a, 0x2f, 0xce, 0xf4, 0x54, 0x54, 0x5e, 0xcc, 0xe9, 0xaa, 0xcc, 0x74,
	0x39, 0xce, 0xf4, 0x94, 0xf3, 0x19, 0x1e, 0x1e, 0x0f, 0x46, 0x43, 0xe6, 0x52, 0x54, 0x38, 0x64,
	0xdf, 0x16, 0x4c, 0xaa, 0xff, 0x20, 0xd4, 0x79, 0x07, 0x8f, 0xd2, 0xc8, 0x72, 0x1e, 0xce, 0x24,
	0x23, 0x2f, 0xa1, 0x8a, 0x26, 0x21, 0xba, 0x79, 0xf8, 0xa0, 0x73, 0x63, 0x59, 0x47, 0x77, 0xea,
	0xba, 0xb3, 0x87, 0x00, 0xa7, 0x5c, 0x2a, 0x4c, 0xcb, 0xf8, 0x6c, 0x4e, 0x1f, 0x76, 0x33, 0xf9,
	0x18, 0xf9, 0x15, 0x6c, 0xe1, 0x4e, 0x69, 0x19, 0xad, 0x72, 0x3e, 0x74, 0xdc, 0xe0, 0xfc, 0x36,
	0x60, 0xef, 0xec, 0xe3, 0xa7, 0xd1, 0x7b, 0xbc, 0xa7, 0x94, 0xf4, 0x95, 0x54, 0x63, 0xad, 0xd4,
	0xd2, 0x3a, 0x4f, 0xcb, 0xeb, 0x3d, 0xad, 0x14, 0x7b, 0x5a, 0x4d, 0x7b, 0xda, 0x80, 0x6d, 0xd7,
	0xf7, 0xc3, 0xef, 0x51, 0x09, 0x5a, 0xc6, 0xc1, 0xf6, 0xb0, 0x86, 0xeb, 0x93, 0xd5, 0x08, 0x9a,
	0x2b, 0x67, 0x9c, 0x3e, 0x3c, 0xbe, 0x25, 0xe4, 0xae, 0x37, 0xfd, 0x03, 0x76, 0xcf, 0xce, 0x47,
	0xe7, 0x38, 0x14, 0x9b, 0xc6, 0x20, 0x71, 0x03, 0xb9, 0x42, 0xcb, 0xc5, 0x42, 0x2b, 0x29, 0xa1,
	0x4e, 0x0f, 0xf6, 0xb2, 0xcc, 0x77, 0x3d, 0xfc, 0x6b, 0xb0, 0x8e, 0x06, 0xa7, 0x83, 0xd1, 0x60,
	0xc8, 0x82, 0xf0, 0xb2, 0xf0, 0xfc, 0xce, 0x13, 0x68, 0xe4, 0xf4, 0x6a, 0xc6, 0xc3, 0x5f, 0x95,
	0x98, 0x92, 0x7c, 0x81, 0xfa, 0xbf, 0xb9, 0x25, 0x4f, 0x93, 0xcc, 0x39, 0x6f, 0xc5, 0x6e, 0xad,
	0x6f, 0xd0, 0xc8, 0x8e, 0xb9, 0xbc, 0xb6, 0x6a, 0x50, 0xed, 0x0a, 0xe6, 0x52, 0xe2, 0x81, 0x99,
	0xd0, 0x4b, 0xf6, 0x93, 0xbb, 0x73, 0x5d, 0xb0, 0x9d, 0xa2, 0x96, 0x98, 0x62, 0x67, 0x79, 0x6d,
	0xd5, 0xa1, 0xd6, 0xd5, 0x2f, 0x9b, 0x70, 0x30, 0x8f, 0x98, 0xcf, 0x56, 0x24, 0xcf, 0x93, 0x08,
	0xeb, 0x6e, 0xcb, 0x7e, 0xb1, 0xa1, 0x2b, 0x43, 0x45, 0x91, 0x80, 0x30, 0x30, 0x13, 0xc3, 0x47,
	0xd2, 0x87, 0xcd, 0x7d, 0x62, 0xf6, 0xb3, 0xc2, 0x9e, 0x0c, 0x8d, 0xfe, 0x94, 0x91, 0xaf, 0x00,
	0x37, 0x4f, 0x9e, 0x64, 0xef, 0xfc, 0xd6, 0x57, 0xc2, 0xde, 0x2f, 0xe8, 0xc8, 0xd8, 0xe2, 0xf3,
	0xc8, 0xc5, 0xe5, 0x55, 0xf3, 0x3e, 0xec, 0xa4, 0x7e, 0x30, 0xcb, 0xab, 0x66, 0x9d, 0xd4, 0x64,
	0x1b, 0x17, 0x93, 0x2d, 0xc4, 0x7a, 0xf3, 0x37, 0x00, 0x00, 0xff, 0xff, 0xe4, 0xf2, 0x98, 0x21,
	0xa4, 0x06, 0x00, 0x00,
}
