// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/lolibrary/lolibrary/service.attribute/proto/attribute.proto

package attributeproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/lolibrary/lolibrary/cmd/protoc-gen-router/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Attribute struct {
	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Slug string `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	Name string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	// timestamps
	CreatedAt            string   `protobuf:"bytes,100,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,101,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Attribute) Reset()         { *m = Attribute{} }
func (m *Attribute) String() string { return proto.CompactTextString(m) }
func (*Attribute) ProtoMessage()    {}
func (*Attribute) Descriptor() ([]byte, []int) {
	return fileDescriptor_c79f94c32f7d1bce, []int{0}
}

func (m *Attribute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Attribute.Unmarshal(m, b)
}
func (m *Attribute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Attribute.Marshal(b, m, deterministic)
}
func (m *Attribute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Attribute.Merge(m, src)
}
func (m *Attribute) XXX_Size() int {
	return xxx_messageInfo_Attribute.Size(m)
}
func (m *Attribute) XXX_DiscardUnknown() {
	xxx_messageInfo_Attribute.DiscardUnknown(m)
}

var xxx_messageInfo_Attribute proto.InternalMessageInfo

func (m *Attribute) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Attribute) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *Attribute) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Attribute) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Attribute) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type AttributeValue struct {
	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AttributeId string `protobuf:"bytes,2,opt,name=attribute_id,json=attributeId,proto3" json:"attribute_id,omitempty"`
	ItemId      string `protobuf:"bytes,3,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Value       string `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	// timestamps
	CreatedAt            string   `protobuf:"bytes,100,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,101,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AttributeValue) Reset()         { *m = AttributeValue{} }
func (m *AttributeValue) String() string { return proto.CompactTextString(m) }
func (*AttributeValue) ProtoMessage()    {}
func (*AttributeValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_c79f94c32f7d1bce, []int{1}
}

func (m *AttributeValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttributeValue.Unmarshal(m, b)
}
func (m *AttributeValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttributeValue.Marshal(b, m, deterministic)
}
func (m *AttributeValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttributeValue.Merge(m, src)
}
func (m *AttributeValue) XXX_Size() int {
	return xxx_messageInfo_AttributeValue.Size(m)
}
func (m *AttributeValue) XXX_DiscardUnknown() {
	xxx_messageInfo_AttributeValue.DiscardUnknown(m)
}

var xxx_messageInfo_AttributeValue proto.InternalMessageInfo

func (m *AttributeValue) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AttributeValue) GetAttributeId() string {
	if m != nil {
		return m.AttributeId
	}
	return ""
}

func (m *AttributeValue) GetItemId() string {
	if m != nil {
		return m.ItemId
	}
	return ""
}

func (m *AttributeValue) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *AttributeValue) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *AttributeValue) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type GETReadAttributeRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Slug                 string   `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GETReadAttributeRequest) Reset()         { *m = GETReadAttributeRequest{} }
func (m *GETReadAttributeRequest) String() string { return proto.CompactTextString(m) }
func (*GETReadAttributeRequest) ProtoMessage()    {}
func (*GETReadAttributeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c79f94c32f7d1bce, []int{2}
}

func (m *GETReadAttributeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GETReadAttributeRequest.Unmarshal(m, b)
}
func (m *GETReadAttributeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GETReadAttributeRequest.Marshal(b, m, deterministic)
}
func (m *GETReadAttributeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GETReadAttributeRequest.Merge(m, src)
}
func (m *GETReadAttributeRequest) XXX_Size() int {
	return xxx_messageInfo_GETReadAttributeRequest.Size(m)
}
func (m *GETReadAttributeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GETReadAttributeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GETReadAttributeRequest proto.InternalMessageInfo

func (m *GETReadAttributeRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GETReadAttributeRequest) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

type GETReadAttributeResponse struct {
	Attribute            *Attribute `protobuf:"bytes,1,opt,name=attribute,proto3" json:"attribute,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GETReadAttributeResponse) Reset()         { *m = GETReadAttributeResponse{} }
func (m *GETReadAttributeResponse) String() string { return proto.CompactTextString(m) }
func (*GETReadAttributeResponse) ProtoMessage()    {}
func (*GETReadAttributeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c79f94c32f7d1bce, []int{3}
}

func (m *GETReadAttributeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GETReadAttributeResponse.Unmarshal(m, b)
}
func (m *GETReadAttributeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GETReadAttributeResponse.Marshal(b, m, deterministic)
}
func (m *GETReadAttributeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GETReadAttributeResponse.Merge(m, src)
}
func (m *GETReadAttributeResponse) XXX_Size() int {
	return xxx_messageInfo_GETReadAttributeResponse.Size(m)
}
func (m *GETReadAttributeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GETReadAttributeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GETReadAttributeResponse proto.InternalMessageInfo

func (m *GETReadAttributeResponse) GetAttribute() *Attribute {
	if m != nil {
		return m.Attribute
	}
	return nil
}

type GETListAttributesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GETListAttributesRequest) Reset()         { *m = GETListAttributesRequest{} }
func (m *GETListAttributesRequest) String() string { return proto.CompactTextString(m) }
func (*GETListAttributesRequest) ProtoMessage()    {}
func (*GETListAttributesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c79f94c32f7d1bce, []int{4}
}

func (m *GETListAttributesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GETListAttributesRequest.Unmarshal(m, b)
}
func (m *GETListAttributesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GETListAttributesRequest.Marshal(b, m, deterministic)
}
func (m *GETListAttributesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GETListAttributesRequest.Merge(m, src)
}
func (m *GETListAttributesRequest) XXX_Size() int {
	return xxx_messageInfo_GETListAttributesRequest.Size(m)
}
func (m *GETListAttributesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GETListAttributesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GETListAttributesRequest proto.InternalMessageInfo

type GETListAttributesResponse struct {
	Attributes           []*Attribute `protobuf:"bytes,1,rep,name=attributes,proto3" json:"attributes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GETListAttributesResponse) Reset()         { *m = GETListAttributesResponse{} }
func (m *GETListAttributesResponse) String() string { return proto.CompactTextString(m) }
func (*GETListAttributesResponse) ProtoMessage()    {}
func (*GETListAttributesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c79f94c32f7d1bce, []int{5}
}

func (m *GETListAttributesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GETListAttributesResponse.Unmarshal(m, b)
}
func (m *GETListAttributesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GETListAttributesResponse.Marshal(b, m, deterministic)
}
func (m *GETListAttributesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GETListAttributesResponse.Merge(m, src)
}
func (m *GETListAttributesResponse) XXX_Size() int {
	return xxx_messageInfo_GETListAttributesResponse.Size(m)
}
func (m *GETListAttributesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GETListAttributesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GETListAttributesResponse proto.InternalMessageInfo

func (m *GETListAttributesResponse) GetAttributes() []*Attribute {
	if m != nil {
		return m.Attributes
	}
	return nil
}

type POSTCreateAttributeRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Slug                 string   `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *POSTCreateAttributeRequest) Reset()         { *m = POSTCreateAttributeRequest{} }
func (m *POSTCreateAttributeRequest) String() string { return proto.CompactTextString(m) }
func (*POSTCreateAttributeRequest) ProtoMessage()    {}
func (*POSTCreateAttributeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c79f94c32f7d1bce, []int{6}
}

func (m *POSTCreateAttributeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_POSTCreateAttributeRequest.Unmarshal(m, b)
}
func (m *POSTCreateAttributeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_POSTCreateAttributeRequest.Marshal(b, m, deterministic)
}
func (m *POSTCreateAttributeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_POSTCreateAttributeRequest.Merge(m, src)
}
func (m *POSTCreateAttributeRequest) XXX_Size() int {
	return xxx_messageInfo_POSTCreateAttributeRequest.Size(m)
}
func (m *POSTCreateAttributeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_POSTCreateAttributeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_POSTCreateAttributeRequest proto.InternalMessageInfo

func (m *POSTCreateAttributeRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *POSTCreateAttributeRequest) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *POSTCreateAttributeRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type POSTCreateAttributeResponse struct {
	Attribute            *Attribute `protobuf:"bytes,1,opt,name=attribute,proto3" json:"attribute,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *POSTCreateAttributeResponse) Reset()         { *m = POSTCreateAttributeResponse{} }
func (m *POSTCreateAttributeResponse) String() string { return proto.CompactTextString(m) }
func (*POSTCreateAttributeResponse) ProtoMessage()    {}
func (*POSTCreateAttributeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c79f94c32f7d1bce, []int{7}
}

func (m *POSTCreateAttributeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_POSTCreateAttributeResponse.Unmarshal(m, b)
}
func (m *POSTCreateAttributeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_POSTCreateAttributeResponse.Marshal(b, m, deterministic)
}
func (m *POSTCreateAttributeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_POSTCreateAttributeResponse.Merge(m, src)
}
func (m *POSTCreateAttributeResponse) XXX_Size() int {
	return xxx_messageInfo_POSTCreateAttributeResponse.Size(m)
}
func (m *POSTCreateAttributeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_POSTCreateAttributeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_POSTCreateAttributeResponse proto.InternalMessageInfo

func (m *POSTCreateAttributeResponse) GetAttribute() *Attribute {
	if m != nil {
		return m.Attribute
	}
	return nil
}

type PUTUpdateAttributeRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PUTUpdateAttributeRequest) Reset()         { *m = PUTUpdateAttributeRequest{} }
func (m *PUTUpdateAttributeRequest) String() string { return proto.CompactTextString(m) }
func (*PUTUpdateAttributeRequest) ProtoMessage()    {}
func (*PUTUpdateAttributeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c79f94c32f7d1bce, []int{8}
}

func (m *PUTUpdateAttributeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PUTUpdateAttributeRequest.Unmarshal(m, b)
}
func (m *PUTUpdateAttributeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PUTUpdateAttributeRequest.Marshal(b, m, deterministic)
}
func (m *PUTUpdateAttributeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PUTUpdateAttributeRequest.Merge(m, src)
}
func (m *PUTUpdateAttributeRequest) XXX_Size() int {
	return xxx_messageInfo_PUTUpdateAttributeRequest.Size(m)
}
func (m *PUTUpdateAttributeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PUTUpdateAttributeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PUTUpdateAttributeRequest proto.InternalMessageInfo

func (m *PUTUpdateAttributeRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PUTUpdateAttributeRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type PUTUpdateAttributeResponse struct {
	Attribute            *Attribute `protobuf:"bytes,1,opt,name=attribute,proto3" json:"attribute,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PUTUpdateAttributeResponse) Reset()         { *m = PUTUpdateAttributeResponse{} }
func (m *PUTUpdateAttributeResponse) String() string { return proto.CompactTextString(m) }
func (*PUTUpdateAttributeResponse) ProtoMessage()    {}
func (*PUTUpdateAttributeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c79f94c32f7d1bce, []int{9}
}

func (m *PUTUpdateAttributeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PUTUpdateAttributeResponse.Unmarshal(m, b)
}
func (m *PUTUpdateAttributeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PUTUpdateAttributeResponse.Marshal(b, m, deterministic)
}
func (m *PUTUpdateAttributeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PUTUpdateAttributeResponse.Merge(m, src)
}
func (m *PUTUpdateAttributeResponse) XXX_Size() int {
	return xxx_messageInfo_PUTUpdateAttributeResponse.Size(m)
}
func (m *PUTUpdateAttributeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PUTUpdateAttributeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PUTUpdateAttributeResponse proto.InternalMessageInfo

func (m *PUTUpdateAttributeResponse) GetAttribute() *Attribute {
	if m != nil {
		return m.Attribute
	}
	return nil
}

type DELETERemoveAttributeRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DELETERemoveAttributeRequest) Reset()         { *m = DELETERemoveAttributeRequest{} }
func (m *DELETERemoveAttributeRequest) String() string { return proto.CompactTextString(m) }
func (*DELETERemoveAttributeRequest) ProtoMessage()    {}
func (*DELETERemoveAttributeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c79f94c32f7d1bce, []int{10}
}

func (m *DELETERemoveAttributeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DELETERemoveAttributeRequest.Unmarshal(m, b)
}
func (m *DELETERemoveAttributeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DELETERemoveAttributeRequest.Marshal(b, m, deterministic)
}
func (m *DELETERemoveAttributeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DELETERemoveAttributeRequest.Merge(m, src)
}
func (m *DELETERemoveAttributeRequest) XXX_Size() int {
	return xxx_messageInfo_DELETERemoveAttributeRequest.Size(m)
}
func (m *DELETERemoveAttributeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DELETERemoveAttributeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DELETERemoveAttributeRequest proto.InternalMessageInfo

func (m *DELETERemoveAttributeRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DELETERemoveAttributeResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DELETERemoveAttributeResponse) Reset()         { *m = DELETERemoveAttributeResponse{} }
func (m *DELETERemoveAttributeResponse) String() string { return proto.CompactTextString(m) }
func (*DELETERemoveAttributeResponse) ProtoMessage()    {}
func (*DELETERemoveAttributeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c79f94c32f7d1bce, []int{11}
}

func (m *DELETERemoveAttributeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DELETERemoveAttributeResponse.Unmarshal(m, b)
}
func (m *DELETERemoveAttributeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DELETERemoveAttributeResponse.Marshal(b, m, deterministic)
}
func (m *DELETERemoveAttributeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DELETERemoveAttributeResponse.Merge(m, src)
}
func (m *DELETERemoveAttributeResponse) XXX_Size() int {
	return xxx_messageInfo_DELETERemoveAttributeResponse.Size(m)
}
func (m *DELETERemoveAttributeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DELETERemoveAttributeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DELETERemoveAttributeResponse proto.InternalMessageInfo

type GETListAttributesByItemRequest struct {
	ItemId               string   `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GETListAttributesByItemRequest) Reset()         { *m = GETListAttributesByItemRequest{} }
func (m *GETListAttributesByItemRequest) String() string { return proto.CompactTextString(m) }
func (*GETListAttributesByItemRequest) ProtoMessage()    {}
func (*GETListAttributesByItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c79f94c32f7d1bce, []int{12}
}

func (m *GETListAttributesByItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GETListAttributesByItemRequest.Unmarshal(m, b)
}
func (m *GETListAttributesByItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GETListAttributesByItemRequest.Marshal(b, m, deterministic)
}
func (m *GETListAttributesByItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GETListAttributesByItemRequest.Merge(m, src)
}
func (m *GETListAttributesByItemRequest) XXX_Size() int {
	return xxx_messageInfo_GETListAttributesByItemRequest.Size(m)
}
func (m *GETListAttributesByItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GETListAttributesByItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GETListAttributesByItemRequest proto.InternalMessageInfo

func (m *GETListAttributesByItemRequest) GetItemId() string {
	if m != nil {
		return m.ItemId
	}
	return ""
}

type GETListAttributesByItemResponse struct {
	Attributes           []*AttributeValue `protobuf:"bytes,1,rep,name=attributes,proto3" json:"attributes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GETListAttributesByItemResponse) Reset()         { *m = GETListAttributesByItemResponse{} }
func (m *GETListAttributesByItemResponse) String() string { return proto.CompactTextString(m) }
func (*GETListAttributesByItemResponse) ProtoMessage()    {}
func (*GETListAttributesByItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c79f94c32f7d1bce, []int{13}
}

func (m *GETListAttributesByItemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GETListAttributesByItemResponse.Unmarshal(m, b)
}
func (m *GETListAttributesByItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GETListAttributesByItemResponse.Marshal(b, m, deterministic)
}
func (m *GETListAttributesByItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GETListAttributesByItemResponse.Merge(m, src)
}
func (m *GETListAttributesByItemResponse) XXX_Size() int {
	return xxx_messageInfo_GETListAttributesByItemResponse.Size(m)
}
func (m *GETListAttributesByItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GETListAttributesByItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GETListAttributesByItemResponse proto.InternalMessageInfo

func (m *GETListAttributesByItemResponse) GetAttributes() []*AttributeValue {
	if m != nil {
		return m.Attributes
	}
	return nil
}

type GETReadAttributeValueRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GETReadAttributeValueRequest) Reset()         { *m = GETReadAttributeValueRequest{} }
func (m *GETReadAttributeValueRequest) String() string { return proto.CompactTextString(m) }
func (*GETReadAttributeValueRequest) ProtoMessage()    {}
func (*GETReadAttributeValueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c79f94c32f7d1bce, []int{14}
}

func (m *GETReadAttributeValueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GETReadAttributeValueRequest.Unmarshal(m, b)
}
func (m *GETReadAttributeValueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GETReadAttributeValueRequest.Marshal(b, m, deterministic)
}
func (m *GETReadAttributeValueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GETReadAttributeValueRequest.Merge(m, src)
}
func (m *GETReadAttributeValueRequest) XXX_Size() int {
	return xxx_messageInfo_GETReadAttributeValueRequest.Size(m)
}
func (m *GETReadAttributeValueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GETReadAttributeValueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GETReadAttributeValueRequest proto.InternalMessageInfo

func (m *GETReadAttributeValueRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GETReadAttributeValueResponse struct {
	Attribute            *AttributeValue `protobuf:"bytes,1,opt,name=attribute,proto3" json:"attribute,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GETReadAttributeValueResponse) Reset()         { *m = GETReadAttributeValueResponse{} }
func (m *GETReadAttributeValueResponse) String() string { return proto.CompactTextString(m) }
func (*GETReadAttributeValueResponse) ProtoMessage()    {}
func (*GETReadAttributeValueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c79f94c32f7d1bce, []int{15}
}

func (m *GETReadAttributeValueResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GETReadAttributeValueResponse.Unmarshal(m, b)
}
func (m *GETReadAttributeValueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GETReadAttributeValueResponse.Marshal(b, m, deterministic)
}
func (m *GETReadAttributeValueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GETReadAttributeValueResponse.Merge(m, src)
}
func (m *GETReadAttributeValueResponse) XXX_Size() int {
	return xxx_messageInfo_GETReadAttributeValueResponse.Size(m)
}
func (m *GETReadAttributeValueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GETReadAttributeValueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GETReadAttributeValueResponse proto.InternalMessageInfo

func (m *GETReadAttributeValueResponse) GetAttribute() *AttributeValue {
	if m != nil {
		return m.Attribute
	}
	return nil
}

type POSTCreateAttributeValueRequest struct {
	AttributeId          string   `protobuf:"bytes,1,opt,name=attribute_id,json=attributeId,proto3" json:"attribute_id,omitempty"`
	ItemId               string   `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Value                string   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *POSTCreateAttributeValueRequest) Reset()         { *m = POSTCreateAttributeValueRequest{} }
func (m *POSTCreateAttributeValueRequest) String() string { return proto.CompactTextString(m) }
func (*POSTCreateAttributeValueRequest) ProtoMessage()    {}
func (*POSTCreateAttributeValueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c79f94c32f7d1bce, []int{16}
}

func (m *POSTCreateAttributeValueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_POSTCreateAttributeValueRequest.Unmarshal(m, b)
}
func (m *POSTCreateAttributeValueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_POSTCreateAttributeValueRequest.Marshal(b, m, deterministic)
}
func (m *POSTCreateAttributeValueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_POSTCreateAttributeValueRequest.Merge(m, src)
}
func (m *POSTCreateAttributeValueRequest) XXX_Size() int {
	return xxx_messageInfo_POSTCreateAttributeValueRequest.Size(m)
}
func (m *POSTCreateAttributeValueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_POSTCreateAttributeValueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_POSTCreateAttributeValueRequest proto.InternalMessageInfo

func (m *POSTCreateAttributeValueRequest) GetAttributeId() string {
	if m != nil {
		return m.AttributeId
	}
	return ""
}

func (m *POSTCreateAttributeValueRequest) GetItemId() string {
	if m != nil {
		return m.ItemId
	}
	return ""
}

func (m *POSTCreateAttributeValueRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type POSTCreateAttributeValueResponse struct {
	Attribute            *AttributeValue `protobuf:"bytes,1,opt,name=attribute,proto3" json:"attribute,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *POSTCreateAttributeValueResponse) Reset()         { *m = POSTCreateAttributeValueResponse{} }
func (m *POSTCreateAttributeValueResponse) String() string { return proto.CompactTextString(m) }
func (*POSTCreateAttributeValueResponse) ProtoMessage()    {}
func (*POSTCreateAttributeValueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c79f94c32f7d1bce, []int{17}
}

func (m *POSTCreateAttributeValueResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_POSTCreateAttributeValueResponse.Unmarshal(m, b)
}
func (m *POSTCreateAttributeValueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_POSTCreateAttributeValueResponse.Marshal(b, m, deterministic)
}
func (m *POSTCreateAttributeValueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_POSTCreateAttributeValueResponse.Merge(m, src)
}
func (m *POSTCreateAttributeValueResponse) XXX_Size() int {
	return xxx_messageInfo_POSTCreateAttributeValueResponse.Size(m)
}
func (m *POSTCreateAttributeValueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_POSTCreateAttributeValueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_POSTCreateAttributeValueResponse proto.InternalMessageInfo

func (m *POSTCreateAttributeValueResponse) GetAttribute() *AttributeValue {
	if m != nil {
		return m.Attribute
	}
	return nil
}

type PUTUpdateAttributeValueRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PUTUpdateAttributeValueRequest) Reset()         { *m = PUTUpdateAttributeValueRequest{} }
func (m *PUTUpdateAttributeValueRequest) String() string { return proto.CompactTextString(m) }
func (*PUTUpdateAttributeValueRequest) ProtoMessage()    {}
func (*PUTUpdateAttributeValueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c79f94c32f7d1bce, []int{18}
}

func (m *PUTUpdateAttributeValueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PUTUpdateAttributeValueRequest.Unmarshal(m, b)
}
func (m *PUTUpdateAttributeValueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PUTUpdateAttributeValueRequest.Marshal(b, m, deterministic)
}
func (m *PUTUpdateAttributeValueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PUTUpdateAttributeValueRequest.Merge(m, src)
}
func (m *PUTUpdateAttributeValueRequest) XXX_Size() int {
	return xxx_messageInfo_PUTUpdateAttributeValueRequest.Size(m)
}
func (m *PUTUpdateAttributeValueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PUTUpdateAttributeValueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PUTUpdateAttributeValueRequest proto.InternalMessageInfo

func (m *PUTUpdateAttributeValueRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PUTUpdateAttributeValueRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type PUTUpdateAttributeValueResponse struct {
	Attribute            *AttributeValue `protobuf:"bytes,1,opt,name=attribute,proto3" json:"attribute,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PUTUpdateAttributeValueResponse) Reset()         { *m = PUTUpdateAttributeValueResponse{} }
func (m *PUTUpdateAttributeValueResponse) String() string { return proto.CompactTextString(m) }
func (*PUTUpdateAttributeValueResponse) ProtoMessage()    {}
func (*PUTUpdateAttributeValueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c79f94c32f7d1bce, []int{19}
}

func (m *PUTUpdateAttributeValueResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PUTUpdateAttributeValueResponse.Unmarshal(m, b)
}
func (m *PUTUpdateAttributeValueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PUTUpdateAttributeValueResponse.Marshal(b, m, deterministic)
}
func (m *PUTUpdateAttributeValueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PUTUpdateAttributeValueResponse.Merge(m, src)
}
func (m *PUTUpdateAttributeValueResponse) XXX_Size() int {
	return xxx_messageInfo_PUTUpdateAttributeValueResponse.Size(m)
}
func (m *PUTUpdateAttributeValueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PUTUpdateAttributeValueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PUTUpdateAttributeValueResponse proto.InternalMessageInfo

func (m *PUTUpdateAttributeValueResponse) GetAttribute() *AttributeValue {
	if m != nil {
		return m.Attribute
	}
	return nil
}

type DELETERemoveAttributeValueRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DELETERemoveAttributeValueRequest) Reset()         { *m = DELETERemoveAttributeValueRequest{} }
func (m *DELETERemoveAttributeValueRequest) String() string { return proto.CompactTextString(m) }
func (*DELETERemoveAttributeValueRequest) ProtoMessage()    {}
func (*DELETERemoveAttributeValueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c79f94c32f7d1bce, []int{20}
}

func (m *DELETERemoveAttributeValueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DELETERemoveAttributeValueRequest.Unmarshal(m, b)
}
func (m *DELETERemoveAttributeValueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DELETERemoveAttributeValueRequest.Marshal(b, m, deterministic)
}
func (m *DELETERemoveAttributeValueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DELETERemoveAttributeValueRequest.Merge(m, src)
}
func (m *DELETERemoveAttributeValueRequest) XXX_Size() int {
	return xxx_messageInfo_DELETERemoveAttributeValueRequest.Size(m)
}
func (m *DELETERemoveAttributeValueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DELETERemoveAttributeValueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DELETERemoveAttributeValueRequest proto.InternalMessageInfo

func (m *DELETERemoveAttributeValueRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DELETERemoveAttributeValueResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DELETERemoveAttributeValueResponse) Reset()         { *m = DELETERemoveAttributeValueResponse{} }
func (m *DELETERemoveAttributeValueResponse) String() string { return proto.CompactTextString(m) }
func (*DELETERemoveAttributeValueResponse) ProtoMessage()    {}
func (*DELETERemoveAttributeValueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c79f94c32f7d1bce, []int{21}
}

func (m *DELETERemoveAttributeValueResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DELETERemoveAttributeValueResponse.Unmarshal(m, b)
}
func (m *DELETERemoveAttributeValueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DELETERemoveAttributeValueResponse.Marshal(b, m, deterministic)
}
func (m *DELETERemoveAttributeValueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DELETERemoveAttributeValueResponse.Merge(m, src)
}
func (m *DELETERemoveAttributeValueResponse) XXX_Size() int {
	return xxx_messageInfo_DELETERemoveAttributeValueResponse.Size(m)
}
func (m *DELETERemoveAttributeValueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DELETERemoveAttributeValueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DELETERemoveAttributeValueResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Attribute)(nil), "attributeproto.Attribute")
	proto.RegisterType((*AttributeValue)(nil), "attributeproto.AttributeValue")
	proto.RegisterType((*GETReadAttributeRequest)(nil), "attributeproto.GETReadAttributeRequest")
	proto.RegisterType((*GETReadAttributeResponse)(nil), "attributeproto.GETReadAttributeResponse")
	proto.RegisterType((*GETListAttributesRequest)(nil), "attributeproto.GETListAttributesRequest")
	proto.RegisterType((*GETListAttributesResponse)(nil), "attributeproto.GETListAttributesResponse")
	proto.RegisterType((*POSTCreateAttributeRequest)(nil), "attributeproto.POSTCreateAttributeRequest")
	proto.RegisterType((*POSTCreateAttributeResponse)(nil), "attributeproto.POSTCreateAttributeResponse")
	proto.RegisterType((*PUTUpdateAttributeRequest)(nil), "attributeproto.PUTUpdateAttributeRequest")
	proto.RegisterType((*PUTUpdateAttributeResponse)(nil), "attributeproto.PUTUpdateAttributeResponse")
	proto.RegisterType((*DELETERemoveAttributeRequest)(nil), "attributeproto.DELETERemoveAttributeRequest")
	proto.RegisterType((*DELETERemoveAttributeResponse)(nil), "attributeproto.DELETERemoveAttributeResponse")
	proto.RegisterType((*GETListAttributesByItemRequest)(nil), "attributeproto.GETListAttributesByItemRequest")
	proto.RegisterType((*GETListAttributesByItemResponse)(nil), "attributeproto.GETListAttributesByItemResponse")
	proto.RegisterType((*GETReadAttributeValueRequest)(nil), "attributeproto.GETReadAttributeValueRequest")
	proto.RegisterType((*GETReadAttributeValueResponse)(nil), "attributeproto.GETReadAttributeValueResponse")
	proto.RegisterType((*POSTCreateAttributeValueRequest)(nil), "attributeproto.POSTCreateAttributeValueRequest")
	proto.RegisterType((*POSTCreateAttributeValueResponse)(nil), "attributeproto.POSTCreateAttributeValueResponse")
	proto.RegisterType((*PUTUpdateAttributeValueRequest)(nil), "attributeproto.PUTUpdateAttributeValueRequest")
	proto.RegisterType((*PUTUpdateAttributeValueResponse)(nil), "attributeproto.PUTUpdateAttributeValueResponse")
	proto.RegisterType((*DELETERemoveAttributeValueRequest)(nil), "attributeproto.DELETERemoveAttributeValueRequest")
	proto.RegisterType((*DELETERemoveAttributeValueResponse)(nil), "attributeproto.DELETERemoveAttributeValueResponse")
}

func init() {
	proto.RegisterFile("github.com/lolibrary/lolibrary/service.attribute/proto/attribute.proto", fileDescriptor_c79f94c32f7d1bce)
}

var fileDescriptor_c79f94c32f7d1bce = []byte{
	// 823 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x97, 0x4d, 0x4f, 0x13, 0x41,
	0x18, 0xc7, 0xb3, 0x2d, 0x2f, 0xe9, 0x53, 0x28, 0x3a, 0x36, 0xb2, 0xac, 0x94, 0xc2, 0xc6, 0x44,
	0x50, 0xbb, 0xab, 0x70, 0x30, 0x24, 0xbe, 0x04, 0xa5, 0x10, 0x12, 0x12, 0x49, 0x29, 0xdc, 0x0c,
	0x6e, 0xbb, 0x13, 0xdc, 0xa4, 0x65, 0x71, 0x77, 0x16, 0xd3, 0x83, 0x07, 0x37, 0xf1, 0x68, 0x3c,
	0xf8, 0x1d, 0x38, 0x7b, 0xe9, 0x27, 0xf2, 0x8b, 0x98, 0x9d, 0x99, 0x6e, 0xf7, 0xbd, 0xab, 0x70,
	0xeb, 0xcc, 0x3c, 0xf3, 0x3c, 0xbf, 0x79, 0x5e, 0xfe, 0x9b, 0xc2, 0xde, 0xb9, 0x41, 0x3e, 0x39,
	0x1d, 0xa5, 0x6b, 0xf6, 0xd5, 0x9e, 0xd9, 0x33, 0x3a, 0x96, 0x66, 0x0d, 0x02, 0xbf, 0x6c, 0x6c,
	0x5d, 0x19, 0x5d, 0xac, 0x68, 0x84, 0x58, 0x46, 0xc7, 0x21, 0x58, 0xbd, 0xb4, 0x4c, 0x62, 0xaa,
	0xfe, 0x5a, 0xa1, 0x6b, 0x54, 0xf1, 0x37, 0xe8, 0x5a, 0xda, 0x9f, 0xe0, 0xb7, 0xdb, 0xd7, 0x99,
	0xa7, 0x6e, 0xe3, 0x1c, 0x5f, 0x34, 0x2c, 0xd3, 0x21, 0xd8, 0xe2, 0xbe, 0xd9, 0x82, 0x39, 0x96,
	0xbf, 0x09, 0x50, 0xda, 0x19, 0xf9, 0x46, 0x15, 0x28, 0x18, 0xba, 0x28, 0xac, 0x0a, 0xeb, 0xa5,
	0x56, 0xc1, 0xd0, 0x11, 0x82, 0x29, 0xbb, 0xe7, 0x9c, 0x8b, 0x05, 0xba, 0x43, 0x7f, 0x7b, 0x7b,
	0x17, 0x5a, 0x1f, 0x8b, 0x53, 0x6c, 0xcf, 0xfb, 0x8d, 0x6a, 0x00, 0x5d, 0x0b, 0x6b, 0x04, 0xeb,
	0x67, 0x1a, 0x11, 0x75, 0x7a, 0x52, 0xe2, 0x3b, 0x3b, 0xc4, 0x3b, 0x76, 0x2e, 0xf5, 0xd1, 0x31,
	0x66, 0xc7, 0x7c, 0x67, 0x87, 0xc8, 0xbf, 0x05, 0xa8, 0xf8, 0x0c, 0xa7, 0x5a, 0xcf, 0x89, 0x83,
	0xac, 0xc1, 0x9c, 0x9f, 0x81, 0x33, 0x43, 0xe7, 0x40, 0x65, 0x7f, 0xef, 0x40, 0x47, 0x8b, 0x30,
	0x6b, 0x10, 0xdc, 0xf7, 0x4e, 0x8b, 0xf4, 0x74, 0xc6, 0x5b, 0x1e, 0xe8, 0xa8, 0x0a, 0xd3, 0x57,
	0x9e, 0x53, 0x4e, 0xcc, 0x16, 0x37, 0x44, 0x7e, 0x05, 0x8b, 0xfb, 0xcd, 0x76, 0x0b, 0x6b, 0xba,
	0x0f, 0xde, 0xc2, 0x9f, 0x1d, 0x6c, 0x93, 0x3c, 0x39, 0x94, 0x8f, 0x41, 0x8c, 0x5f, 0xb7, 0x2f,
	0xcd, 0x0b, 0x1b, 0xa3, 0x17, 0x50, 0xf2, 0x9f, 0x45, 0xdd, 0x94, 0x37, 0x97, 0x94, 0x70, 0xf9,
	0x95, 0xf1, 0xad, 0xb1, 0xad, 0x2c, 0x51, 0xa7, 0x87, 0x86, 0x4d, 0xfc, 0x63, 0x9b, 0x43, 0xc9,
	0xa7, 0xb0, 0x94, 0x70, 0xc6, 0x23, 0x6e, 0x03, 0xf8, 0x5e, 0x6c, 0x51, 0x58, 0x2d, 0x66, 0x87,
	0x0c, 0x18, 0xcb, 0x6d, 0x90, 0x8e, 0xde, 0x1f, 0xb7, 0xdf, 0xd1, 0xbc, 0xfd, 0x4f, 0x2a, 0xfc,
	0x76, 0x2a, 0x8e, 0xdb, 0x49, 0x3e, 0x85, 0x07, 0x89, 0x5e, 0x6f, 0x9a, 0xa1, 0x37, 0xb0, 0x74,
	0x74, 0xd2, 0x3e, 0xa1, 0x55, 0xcc, 0x03, 0x4b, 0xc1, 0x0a, 0x01, 0xb0, 0x13, 0x90, 0x92, 0x1c,
	0xdc, 0x94, 0x4b, 0x81, 0xe5, 0xdd, 0xe6, 0x61, 0xb3, 0xdd, 0x6c, 0xe1, 0xbe, 0x79, 0x35, 0x11,
	0x4d, 0xae, 0x43, 0x2d, 0xc5, 0x9e, 0x91, 0xc8, 0xdb, 0xb0, 0x12, 0x2b, 0xf7, 0xdb, 0xc1, 0x01,
	0xc1, 0xfd, 0x91, 0xcb, 0xc0, 0xb4, 0x08, 0xc1, 0x69, 0x91, 0x35, 0xa8, 0xa7, 0x5e, 0xe5, 0xef,
	0x7c, 0x9d, 0xd0, 0x2f, 0x2b, 0xa9, 0x0f, 0xa5, 0x03, 0x1d, 0x6a, 0x1a, 0x05, 0x96, 0xa3, 0xdd,
	0xcf, 0x8c, 0x52, 0x9e, 0xfb, 0x01, 0x6a, 0x29, 0xf6, 0x1c, 0xe8, 0x65, 0x3c, 0xf1, 0x93, 0x78,
	0x02, 0xd9, 0xb7, 0xa1, 0x9e, 0xd0, 0x6d, 0x21, 0xa2, 0xa8, 0xfc, 0x08, 0x99, 0xf2, 0x53, 0x48,
	0x96, 0x9f, 0x62, 0x40, 0x7e, 0xe4, 0x8f, 0xb0, 0x9a, 0x1e, 0xf4, 0x56, 0x9e, 0xb5, 0x07, 0x2b,
	0xf1, 0x5e, 0xcd, 0xca, 0xf3, 0x98, 0xb4, 0x10, 0x24, 0x3d, 0x83, 0x7a, 0xaa, 0x9f, 0x5b, 0x01,
	0xdd, 0x82, 0xb5, 0xc4, 0x6e, 0xce, 0xec, 0x89, 0x87, 0x20, 0x67, 0x5d, 0x62, 0x60, 0x9b, 0x7f,
	0x20, 0x40, 0x86, 0x4c, 0x98, 0x0f, 0x35, 0x11, 0x7a, 0x14, 0x85, 0x4c, 0xd1, 0x74, 0x69, 0x7d,
	0xb2, 0x21, 0x9f, 0xbc, 0xb2, 0x3b, 0x14, 0x67, 0x61, 0x5a, 0xb5, 0xb0, 0xa6, 0xa3, 0x2f, 0xb0,
	0x10, 0xc9, 0x1b, 0xda, 0x88, 0x7a, 0x4a, 0x15, 0x24, 0xe9, 0x71, 0x1e, 0x53, 0x1e, 0x76, 0xde,
	0x1d, 0x8a, 0x25, 0x98, 0x55, 0xd9, 0x17, 0x0a, 0x7d, 0x85, 0x85, 0x5d, 0xdc, 0xc3, 0xc1, 0xc0,
	0x4f, 0xa3, 0xde, 0xb2, 0x14, 0x47, 0x6a, 0xe4, 0xb4, 0x8e, 0x84, 0xd7, 0x69, 0x50, 0x34, 0x80,
	0x85, 0x48, 0x63, 0xa3, 0xf8, 0x63, 0x52, 0x3f, 0x1b, 0xd2, 0x93, 0x5c, 0xb6, 0x91, 0xd0, 0xec,
	0xd3, 0x8d, 0x2c, 0xa8, 0x84, 0xb5, 0x0b, 0x25, 0xd5, 0x2e, 0xf1, 0x23, 0x29, 0x6d, 0xe4, 0xb0,
	0x8c, 0x94, 0xb9, 0x67, 0xd8, 0x04, 0xfd, 0x12, 0xa0, 0x9a, 0x24, 0x98, 0x48, 0x99, 0xe8, 0x30,
	0x24, 0xca, 0x92, 0x9a, 0xdb, 0x9e, 0x63, 0x48, 0xee, 0x50, 0xbc, 0x0f, 0x55, 0x95, 0x4e, 0xaa,
	0xdd, 0xe8, 0x0c, 0x1a, 0x9e, 0xe8, 0x30, 0xaa, 0xef, 0x02, 0xa0, 0xb8, 0x66, 0xc6, 0xfb, 0x20,
	0x4b, 0x8a, 0xe3, 0x7d, 0x90, 0x29, 0xc4, 0x32, 0x72, 0x87, 0x62, 0x05, 0xe6, 0x38, 0x0f, 0x1b,
	0x82, 0x9f, 0x02, 0x54, 0x93, 0x64, 0x0e, 0xa9, 0x39, 0xca, 0x1c, 0x82, 0x79, 0x96, 0xff, 0x02,
	0xe7, 0xa9, 0xba, 0x43, 0xf1, 0x0e, 0x54, 0x46, 0x3c, 0xbc, 0x47, 0x7e, 0x08, 0x50, 0x4d, 0xd2,
	0xb3, 0x78, 0xbd, 0xb2, 0x05, 0x34, 0x5e, 0xaf, 0x09, 0x42, 0x19, 0xe5, 0xe1, 0xd3, 0xea, 0xf5,
	0x4f, 0x64, 0x5c, 0x19, 0xcf, 0xf3, 0x5c, 0x53, 0x18, 0x42, 0xda, 0xfc, 0x97, 0x2b, 0xc9, 0x54,
	0x6c, 0x88, 0xa5, 0x75, 0xf7, 0xba, 0x76, 0x0f, 0xee, 0xc6, 0xfe, 0xa1, 0xb8, 0xd7, 0xb5, 0x79,
	0x54, 0xb6, 0x1b, 0xfe, 0x46, 0x67, 0x86, 0x46, 0xda, 0xfa, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xef,
	0xb7, 0xc1, 0x56, 0xed, 0x0c, 0x00, 0x00,
}
