// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/lolibrary/lolibrary/service.user/proto/user.proto

package userproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/lolibrary/lolibrary/cmd/protoc-gen-router/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email    string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Username string `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Name     string `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Role     string `protobuf:"bytes,6,opt,name=role,proto3" json:"role,omitempty"`
	// general-purpose metadata as an annotation.
	// stored in the database as JSON.
	Metadata             map[string]string `protobuf:"bytes,50,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Verified             bool              `protobuf:"varint,51,opt,name=verified,proto3" json:"verified,omitempty"`
	Banned               bool              `protobuf:"varint,52,opt,name=banned,proto3" json:"banned,omitempty"`
	CreatedAt            string            `protobuf:"bytes,100,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string            `protobuf:"bytes,101,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	VerifiedAt           string            `protobuf:"bytes,102,opt,name=verified_at,json=verifiedAt,proto3" json:"verified_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_23346f021e69d8ab, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *User) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *User) GetVerified() bool {
	if m != nil {
		return m.Verified
	}
	return false
}

func (m *User) GetBanned() bool {
	if m != nil {
		return m.Banned
	}
	return false
}

func (m *User) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *User) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *User) GetVerifiedAt() string {
	if m != nil {
		return m.VerifiedAt
	}
	return ""
}

type POSTCreateUserRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *POSTCreateUserRequest) Reset()         { *m = POSTCreateUserRequest{} }
func (m *POSTCreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*POSTCreateUserRequest) ProtoMessage()    {}
func (*POSTCreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_23346f021e69d8ab, []int{1}
}

func (m *POSTCreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_POSTCreateUserRequest.Unmarshal(m, b)
}
func (m *POSTCreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_POSTCreateUserRequest.Marshal(b, m, deterministic)
}
func (m *POSTCreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_POSTCreateUserRequest.Merge(m, src)
}
func (m *POSTCreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_POSTCreateUserRequest.Size(m)
}
func (m *POSTCreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_POSTCreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_POSTCreateUserRequest proto.InternalMessageInfo

func (m *POSTCreateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *POSTCreateUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *POSTCreateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *POSTCreateUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type POSTCreateUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *POSTCreateUserResponse) Reset()         { *m = POSTCreateUserResponse{} }
func (m *POSTCreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*POSTCreateUserResponse) ProtoMessage()    {}
func (*POSTCreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_23346f021e69d8ab, []int{2}
}

func (m *POSTCreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_POSTCreateUserResponse.Unmarshal(m, b)
}
func (m *POSTCreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_POSTCreateUserResponse.Marshal(b, m, deterministic)
}
func (m *POSTCreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_POSTCreateUserResponse.Merge(m, src)
}
func (m *POSTCreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_POSTCreateUserResponse.Size(m)
}
func (m *POSTCreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_POSTCreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_POSTCreateUserResponse proto.InternalMessageInfo

func (m *POSTCreateUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "userproto.User")
	proto.RegisterMapType((map[string]string)(nil), "userproto.User.MetadataEntry")
	proto.RegisterType((*POSTCreateUserRequest)(nil), "userproto.POSTCreateUserRequest")
	proto.RegisterType((*POSTCreateUserResponse)(nil), "userproto.POSTCreateUserResponse")
}

func init() {
	proto.RegisterFile("github.com/lolibrary/lolibrary/service.user/proto/user.proto", fileDescriptor_23346f021e69d8ab)
}

var fileDescriptor_23346f021e69d8ab = []byte{
	// 450 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0xcd, 0x8e, 0xd3, 0x30,
	0x10, 0x56, 0x7e, 0xb6, 0xb4, 0x53, 0x76, 0x41, 0x16, 0xac, 0xac, 0x48, 0x85, 0x52, 0x2e, 0xbd,
	0x34, 0x95, 0xba, 0x1c, 0xf8, 0x3d, 0x54, 0x08, 0x71, 0x42, 0xa0, 0x00, 0x67, 0x70, 0xe3, 0xd9,
	0x25, 0x22, 0x89, 0x8b, 0xed, 0x14, 0xe5, 0xda, 0x13, 0x6f, 0xc0, 0x1b, 0xec, 0x1b, 0xf0, 0x7e,
	0xc8, 0x76, 0x92, 0x96, 0x15, 0xdb, 0xbd, 0x7d, 0x3f, 0x93, 0x99, 0xf1, 0x7c, 0x0a, 0xbc, 0xbc,
	0xc8, 0xf4, 0xb7, 0x6a, 0x15, 0xa7, 0xa2, 0x98, 0xe7, 0x22, 0xcf, 0x56, 0x92, 0xc9, 0x7a, 0x0f,
	0x29, 0x94, 0x9b, 0x2c, 0xc5, 0xb8, 0x52, 0x28, 0xe7, 0x6b, 0x29, 0xb4, 0x98, 0x1b, 0x18, 0x5b,
	0x48, 0x06, 0x06, 0x5b, 0x18, 0xbd, 0xbd, 0xa1, 0x51, 0x5a, 0x70, 0xf7, 0x7d, 0x3a, 0xbb, 0xc0,
	0x72, 0x26, 0x45, 0xa5, 0xbb, 0x8e, 0x8e, 0xb8, 0x9e, 0x93, 0xdf, 0x01, 0x84, 0x9f, 0x15, 0x4a,
	0x72, 0x02, 0x7e, 0xc6, 0xa9, 0x37, 0xf6, 0xa6, 0x83, 0xc4, 0xcf, 0x38, 0xb9, 0x07, 0x47, 0x58,
	0xb0, 0x2c, 0xa7, 0xbe, 0x95, 0x1c, 0x21, 0x11, 0xf4, 0xcd, 0x12, 0x25, 0x2b, 0x90, 0x06, 0xd6,
	0xe8, 0xb8, 0xf1, 0xd6, 0x4c, 0xa9, 0x9f, 0x42, 0x72, 0x1a, 0x3a, 0xaf, 0xe5, 0x84, 0x40, 0x68,
	0xbf, 0x39, 0xb2, 0xba, 0xc5, 0x46, 0x93, 0x22, 0x47, 0xda, 0x73, 0x9a, 0xc1, 0xe4, 0x19, 0xf4,
	0x0b, 0xd4, 0x8c, 0x33, 0xcd, 0xe8, 0x62, 0x1c, 0x4c, 0x87, 0x8b, 0x51, 0xdc, 0xbd, 0x3a, 0x36,
	0x8b, 0xc6, 0xef, 0x1a, 0xff, 0x4d, 0xa9, 0x65, 0x9d, 0x74, 0xe5, 0x66, 0xfc, 0x06, 0x65, 0x76,
	0x9e, 0x21, 0xa7, 0x67, 0x63, 0x6f, 0xda, 0x4f, 0x3a, 0x4e, 0x4e, 0xa1, 0xb7, 0x62, 0x65, 0x89,
	0x9c, 0x3e, 0xb1, 0x4e, 0xc3, 0xc8, 0x08, 0x20, 0x95, 0xc8, 0x34, 0xf2, 0x2f, 0x4c, 0x53, 0x6e,
	0x17, 0x19, 0x34, 0xca, 0x52, 0x1b, 0xbb, 0x5a, 0xf3, 0xd6, 0x46, 0x67, 0x37, 0xca, 0x52, 0x93,
	0x87, 0x30, 0x6c, 0x27, 0x18, 0xff, 0xdc, 0xfa, 0xd0, 0x4a, 0x4b, 0x1d, 0xbd, 0x80, 0xe3, 0x7f,
	0xb6, 0x25, 0x77, 0x21, 0xf8, 0x8e, 0x75, 0x73, 0x65, 0x03, 0xcd, 0x99, 0x37, 0x2c, 0xaf, 0xb0,
	0x3d, 0xb3, 0x25, 0xcf, 0xfd, 0xa7, 0xde, 0xa4, 0x86, 0xfb, 0x1f, 0xde, 0x7f, 0xfc, 0xf4, 0xda,
	0x6e, 0x63, 0x5e, 0x9e, 0xe0, 0x8f, 0x0a, 0x95, 0xde, 0x25, 0xe3, 0x5d, 0x97, 0x8c, 0x7f, 0x20,
	0x99, 0xe0, 0x9a, 0x64, 0xc2, 0x5d, 0x32, 0x93, 0x57, 0x70, 0x7a, 0x75, 0xb4, 0x5a, 0x8b, 0x52,
	0x21, 0x79, 0x0c, 0xa1, 0xe9, 0x6a, 0x47, 0x0f, 0x17, 0x77, 0xae, 0x64, 0x93, 0x58, 0x73, 0xf1,
	0xcb, 0x73, 0x55, 0xe4, 0x2b, 0xc0, 0xae, 0x07, 0x19, 0xef, 0x55, 0xff, 0xf7, 0x65, 0xd1, 0xa3,
	0x03, 0x15, 0x6e, 0x81, 0xc9, 0xf1, 0xf6, 0x0f, 0x1d, 0xc0, 0xad, 0xb9, 0x0b, 0x29, 0x7a, 0xb0,
	0xbd, 0x1c, 0x9d, 0xc0, 0xed, 0xfd, 0xff, 0x66, 0x7b, 0x39, 0xea, 0x93, 0x9e, 0x9a, 0x19, 0xbc,
	0xea, 0xd9, 0x66, 0x67, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x3f, 0x23, 0x38, 0x60, 0x79, 0x03,
	0x00, 0x00,
}
