// Code generated by protoc-gen-gotemplate; DO NOT EDIT.

package idproto

import (
	"context"

	"github.com/monzo/typhon"
)

// -------------------------
// POST /service.id/generate/flake
// -------------------------

// Method is the HTTP method used for this request.
// It is inferred from the name of the Request using a prefix match.
func (body POSTGenerateFlakeRequest) Method() string {
	return "POST"
}

// Path is the HTTP path to this endpoint
func (body POSTGenerateFlakeRequest) Path() string {
	return "/generate/flake"
}

// ServiceName is the long-form service name, e.g. service.brand.
func (body POSTGenerateFlakeRequest) ServiceName() string {
	return "service.id"
}

// Host is the short-form service name, e.g. s-brand.
func (body POSTGenerateFlakeRequest) Host() string {
	return "s-id"
}

// FullPath is the full routable URL to this service.
func (body POSTGenerateFlakeRequest) FullPath() string {
	return "http://s-id/generate/flake"
}

// Request returns a typhon request for this type.
func (body POSTGenerateFlakeRequest) Request(ctx context.Context) typhon.Request {
	return typhon.NewRequest(ctx, body.Method(), body.FullPath(), body)
}

// Response is a shortcut for .Send(ctx).DecodeResponse(), for when you do not need a future.
// This saves on boilerplate throughout the codebase and you should use this method unless you need parallel requests.
func (body POSTGenerateFlakeRequest) Response(ctx context.Context) (*POSTGenerateFlakeResponse, error) {
	return body.Send(ctx).DecodeResponse()
}

// Send creates a typhon future and immediately returns it.
// To wait for the request to complete and return the response, use DecodeResponse on the returned future.
func (body POSTGenerateFlakeRequest) Send(ctx context.Context) *POSTGenerateFlakeFuture {
	return &POSTGenerateFlakeFuture{Future: body.Request(ctx).Send()}
}

// SendVia creates a typhon future and immediately returns it, passing the request through svc.
// To wait for the request to complete and return the response, use DecodeResponse on the returned future.
func (body POSTGenerateFlakeRequest) SendVia(ctx context.Context, svc typhon.Service) *POSTGenerateFlakeFuture {
	return &POSTGenerateFlakeFuture{Future: body.Request(ctx).SendVia(svc)}
}

// POSTGenerateFlakeFuture is an intermediate future used for parallel requests with POSTGenerateFlakeRequest
type POSTGenerateFlakeFuture struct {
	Future   *typhon.ResponseFuture
	Response *typhon.Response
}

// Done waits for a response from a typhon future, and is safe to call multiple times in a row.
func (f *POSTGenerateFlakeFuture) Done() {
	if f.Response == nil {
		rsp := f.Future.Response()
		f.Response = &rsp
	}
}

// DecodeResponse waits for this future to be done and then decodes the response into a concrete type.
func (f *POSTGenerateFlakeFuture) DecodeResponse() (*POSTGenerateFlakeResponse, error) {
	f.Done()

	body := &POSTGenerateFlakeResponse{}
	if err := f.Response.Decode(body); err != nil {
		return nil, err
	}

	return body, nil
}
