// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/lolibrary/lolibrary/service.item/proto/item.proto

package itemproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/lolibrary/lolibrary/cmd/protoc-gen-router/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Item struct {
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Slug          string `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	BrandId       string `protobuf:"bytes,3,opt,name=brand_id,json=brandId,proto3" json:"brand_id,omitempty"`
	CategoryId    string `protobuf:"bytes,4,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	UserId        string `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ImageId       string `protobuf:"bytes,6,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	PublisherId   string `protobuf:"bytes,7,opt,name=publisher_id,json=publisherId,proto3" json:"publisher_id,omitempty"`
	EnglishName   string `protobuf:"bytes,8,opt,name=english_name,json=englishName,proto3" json:"english_name,omitempty"`
	ForeignName   string `protobuf:"bytes,9,opt,name=foreign_name,json=foreignName,proto3" json:"foreign_name,omitempty"`
	ProductNumber string `protobuf:"bytes,10,opt,name=product_number,json=productNumber,proto3" json:"product_number,omitempty"`
	Currency      string `protobuf:"bytes,11,opt,name=currency,proto3" json:"currency,omitempty"`
	Price         string `protobuf:"bytes,12,opt,name=price,proto3" json:"price,omitempty"`
	Year          int32  `protobuf:"varint,13,opt,name=year,proto3" json:"year,omitempty"`
	Notes         string `protobuf:"bytes,14,opt,name=notes,proto3" json:"notes,omitempty"`
	// status is used for draft/non-draft but could be a bitmask later.
	Status int32 `protobuf:"varint,40,opt,name=status,proto3" json:"status,omitempty"`
	// key-value searchable metadata.
	Metadata map[string]string `protobuf:"bytes,50,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// timestamps
	CreatedAt            string   `protobuf:"bytes,100,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,101,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	PublishedAt          string   `protobuf:"bytes,102,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bafc3b3eeda8c31, []int{0}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Item) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *Item) GetBrandId() string {
	if m != nil {
		return m.BrandId
	}
	return ""
}

func (m *Item) GetCategoryId() string {
	if m != nil {
		return m.CategoryId
	}
	return ""
}

func (m *Item) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Item) GetImageId() string {
	if m != nil {
		return m.ImageId
	}
	return ""
}

func (m *Item) GetPublisherId() string {
	if m != nil {
		return m.PublisherId
	}
	return ""
}

func (m *Item) GetEnglishName() string {
	if m != nil {
		return m.EnglishName
	}
	return ""
}

func (m *Item) GetForeignName() string {
	if m != nil {
		return m.ForeignName
	}
	return ""
}

func (m *Item) GetProductNumber() string {
	if m != nil {
		return m.ProductNumber
	}
	return ""
}

func (m *Item) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *Item) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *Item) GetYear() int32 {
	if m != nil {
		return m.Year
	}
	return 0
}

func (m *Item) GetNotes() string {
	if m != nil {
		return m.Notes
	}
	return ""
}

func (m *Item) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Item) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Item) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Item) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *Item) GetPublishedAt() string {
	if m != nil {
		return m.PublishedAt
	}
	return ""
}

type GETReadItemRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Slug                 string   `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GETReadItemRequest) Reset()         { *m = GETReadItemRequest{} }
func (m *GETReadItemRequest) String() string { return proto.CompactTextString(m) }
func (*GETReadItemRequest) ProtoMessage()    {}
func (*GETReadItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bafc3b3eeda8c31, []int{1}
}

func (m *GETReadItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GETReadItemRequest.Unmarshal(m, b)
}
func (m *GETReadItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GETReadItemRequest.Marshal(b, m, deterministic)
}
func (m *GETReadItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GETReadItemRequest.Merge(m, src)
}
func (m *GETReadItemRequest) XXX_Size() int {
	return xxx_messageInfo_GETReadItemRequest.Size(m)
}
func (m *GETReadItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GETReadItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GETReadItemRequest proto.InternalMessageInfo

func (m *GETReadItemRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GETReadItemRequest) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

type GETReadItemResponse struct {
	Item                 *Item    `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GETReadItemResponse) Reset()         { *m = GETReadItemResponse{} }
func (m *GETReadItemResponse) String() string { return proto.CompactTextString(m) }
func (*GETReadItemResponse) ProtoMessage()    {}
func (*GETReadItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bafc3b3eeda8c31, []int{2}
}

func (m *GETReadItemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GETReadItemResponse.Unmarshal(m, b)
}
func (m *GETReadItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GETReadItemResponse.Marshal(b, m, deterministic)
}
func (m *GETReadItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GETReadItemResponse.Merge(m, src)
}
func (m *GETReadItemResponse) XXX_Size() int {
	return xxx_messageInfo_GETReadItemResponse.Size(m)
}
func (m *GETReadItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GETReadItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GETReadItemResponse proto.InternalMessageInfo

func (m *GETReadItemResponse) GetItem() *Item {
	if m != nil {
		return m.Item
	}
	return nil
}

type POSTCreateItemRequest struct {
	Id         string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Slug       string `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	BrandId    string `protobuf:"bytes,3,opt,name=brand_id,json=brandId,proto3" json:"brand_id,omitempty"`
	CategoryId string `protobuf:"bytes,4,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	UserId     string `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ImageId    string `protobuf:"bytes,6,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	// no publisher id or timestamps on creation
	EnglishName          string   `protobuf:"bytes,8,opt,name=english_name,json=englishName,proto3" json:"english_name,omitempty"`
	ForeignName          string   `protobuf:"bytes,9,opt,name=foreign_name,json=foreignName,proto3" json:"foreign_name,omitempty"`
	ProductNumber        string   `protobuf:"bytes,10,opt,name=product_number,json=productNumber,proto3" json:"product_number,omitempty"`
	Currency             string   `protobuf:"bytes,11,opt,name=currency,proto3" json:"currency,omitempty"`
	Price                string   `protobuf:"bytes,12,opt,name=price,proto3" json:"price,omitempty"`
	Year                 int32    `protobuf:"varint,13,opt,name=year,proto3" json:"year,omitempty"`
	Notes                string   `protobuf:"bytes,14,opt,name=notes,proto3" json:"notes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *POSTCreateItemRequest) Reset()         { *m = POSTCreateItemRequest{} }
func (m *POSTCreateItemRequest) String() string { return proto.CompactTextString(m) }
func (*POSTCreateItemRequest) ProtoMessage()    {}
func (*POSTCreateItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bafc3b3eeda8c31, []int{3}
}

func (m *POSTCreateItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_POSTCreateItemRequest.Unmarshal(m, b)
}
func (m *POSTCreateItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_POSTCreateItemRequest.Marshal(b, m, deterministic)
}
func (m *POSTCreateItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_POSTCreateItemRequest.Merge(m, src)
}
func (m *POSTCreateItemRequest) XXX_Size() int {
	return xxx_messageInfo_POSTCreateItemRequest.Size(m)
}
func (m *POSTCreateItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_POSTCreateItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_POSTCreateItemRequest proto.InternalMessageInfo

func (m *POSTCreateItemRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *POSTCreateItemRequest) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *POSTCreateItemRequest) GetBrandId() string {
	if m != nil {
		return m.BrandId
	}
	return ""
}

func (m *POSTCreateItemRequest) GetCategoryId() string {
	if m != nil {
		return m.CategoryId
	}
	return ""
}

func (m *POSTCreateItemRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *POSTCreateItemRequest) GetImageId() string {
	if m != nil {
		return m.ImageId
	}
	return ""
}

func (m *POSTCreateItemRequest) GetEnglishName() string {
	if m != nil {
		return m.EnglishName
	}
	return ""
}

func (m *POSTCreateItemRequest) GetForeignName() string {
	if m != nil {
		return m.ForeignName
	}
	return ""
}

func (m *POSTCreateItemRequest) GetProductNumber() string {
	if m != nil {
		return m.ProductNumber
	}
	return ""
}

func (m *POSTCreateItemRequest) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *POSTCreateItemRequest) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *POSTCreateItemRequest) GetYear() int32 {
	if m != nil {
		return m.Year
	}
	return 0
}

func (m *POSTCreateItemRequest) GetNotes() string {
	if m != nil {
		return m.Notes
	}
	return ""
}

type POSTCreateItemResponse struct {
	Item                 *Item    `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *POSTCreateItemResponse) Reset()         { *m = POSTCreateItemResponse{} }
func (m *POSTCreateItemResponse) String() string { return proto.CompactTextString(m) }
func (*POSTCreateItemResponse) ProtoMessage()    {}
func (*POSTCreateItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bafc3b3eeda8c31, []int{4}
}

func (m *POSTCreateItemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_POSTCreateItemResponse.Unmarshal(m, b)
}
func (m *POSTCreateItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_POSTCreateItemResponse.Marshal(b, m, deterministic)
}
func (m *POSTCreateItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_POSTCreateItemResponse.Merge(m, src)
}
func (m *POSTCreateItemResponse) XXX_Size() int {
	return xxx_messageInfo_POSTCreateItemResponse.Size(m)
}
func (m *POSTCreateItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_POSTCreateItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_POSTCreateItemResponse proto.InternalMessageInfo

func (m *POSTCreateItemResponse) GetItem() *Item {
	if m != nil {
		return m.Item
	}
	return nil
}

func init() {
	proto.RegisterType((*Item)(nil), "itemproto.Item")
	proto.RegisterMapType((map[string]string)(nil), "itemproto.Item.MetadataEntry")
	proto.RegisterType((*GETReadItemRequest)(nil), "itemproto.GETReadItemRequest")
	proto.RegisterType((*GETReadItemResponse)(nil), "itemproto.GETReadItemResponse")
	proto.RegisterType((*POSTCreateItemRequest)(nil), "itemproto.POSTCreateItemRequest")
	proto.RegisterType((*POSTCreateItemResponse)(nil), "itemproto.POSTCreateItemResponse")
}

func init() {
	proto.RegisterFile("github.com/lolibrary/lolibrary/service.item/proto/item.proto", fileDescriptor_3bafc3b3eeda8c31)
}

var fileDescriptor_3bafc3b3eeda8c31 = []byte{
	// 608 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x54, 0xcd, 0x6e, 0x13, 0x3f,
	0x10, 0x57, 0xd2, 0x7c, 0x4e, 0x9a, 0xfc, 0xff, 0x32, 0x50, 0x4c, 0xa4, 0x94, 0x34, 0x08, 0x29,
	0x97, 0x26, 0x52, 0xb8, 0x94, 0x02, 0x87, 0x0a, 0x55, 0x55, 0x0e, 0x14, 0x14, 0x2a, 0xae, 0xc1,
	0xbb, 0x9e, 0x6e, 0x57, 0x64, 0x3f, 0xf0, 0xda, 0x95, 0xf6, 0x9a, 0x87, 0xe9, 0x1b, 0xf4, 0x7d,
	0x78, 0x08, 0x24, 0xae, 0xc8, 0xe3, 0x6d, 0x48, 0xcb, 0x67, 0x4f, 0x48, 0xdc, 0x7e, 0x5f, 0x33,
	0xce, 0x8e, 0xc7, 0x81, 0xe7, 0x41, 0xa8, 0xcf, 0x8c, 0x37, 0xf2, 0x93, 0x68, 0xbc, 0x48, 0x16,
	0xa1, 0xa7, 0x84, 0xca, 0xd7, 0x50, 0x86, 0xea, 0x3c, 0xf4, 0x71, 0x14, 0x6a, 0x8c, 0xc6, 0xa9,
	0x4a, 0x74, 0x32, 0xb6, 0x70, 0x44, 0x90, 0x35, 0x2d, 0x26, 0xd8, 0x3d, 0xfa, 0x4d, 0x23, 0x3f,
	0x92, 0xae, 0xde, 0xdf, 0x0d, 0x30, 0xde, 0x55, 0x89, 0xd1, 0xa8, 0x8a, 0x8e, 0x8e, 0xb8, 0x9e,
	0x83, 0x2f, 0x15, 0xa8, 0x4c, 0x35, 0x46, 0xac, 0x03, 0xe5, 0x50, 0xf2, 0x52, 0xbf, 0x34, 0x6c,
	0xce, 0xca, 0xa1, 0x64, 0x0c, 0x2a, 0xd9, 0xc2, 0x04, 0xbc, 0x4c, 0x0a, 0x61, 0xf6, 0x00, 0x1a,
	0x9e, 0x12, 0xb1, 0x9c, 0x87, 0x92, 0x6f, 0x90, 0x5e, 0x27, 0x3e, 0x95, 0xec, 0x21, 0xb4, 0x7c,
	0xa1, 0x31, 0x48, 0x54, 0x6e, 0xdd, 0x0a, 0xb9, 0x70, 0x25, 0x4d, 0x25, 0xbb, 0x0f, 0x75, 0x93,
	0xa1, 0xb2, 0x66, 0x95, 0xcc, 0x9a, 0xa5, 0x53, 0x69, 0x9b, 0x86, 0x91, 0x08, 0xd0, 0x3a, 0x35,
	0xd7, 0x94, 0xf8, 0x54, 0xb2, 0x1d, 0xd8, 0x4c, 0x8d, 0xb7, 0x08, 0xb3, 0x33, 0x57, 0x58, 0x27,
	0xbb, 0xb5, 0xd2, 0x5c, 0x04, 0xe3, 0xc0, 0xd2, 0x79, 0x2c, 0x22, 0xe4, 0x0d, 0x17, 0x29, 0xb4,
	0x63, 0x11, 0xa1, 0x8d, 0x9c, 0x26, 0x0a, 0xc3, 0x20, 0x76, 0x91, 0xa6, 0x8b, 0x14, 0x1a, 0x45,
	0x1e, 0x43, 0x27, 0x55, 0x89, 0x34, 0xbe, 0x9e, 0xc7, 0x26, 0xf2, 0x50, 0x71, 0xa0, 0x50, 0xbb,
	0x50, 0x8f, 0x49, 0x64, 0x5d, 0x68, 0xf8, 0x46, 0x29, 0x8c, 0xfd, 0x9c, 0xb7, 0x28, 0xb0, 0xe2,
	0xec, 0x2e, 0x54, 0x53, 0x15, 0xfa, 0xc8, 0x37, 0xc9, 0x70, 0xc4, 0x4e, 0x31, 0x47, 0xa1, 0x78,
	0xbb, 0x5f, 0x1a, 0x56, 0x67, 0x84, 0x6d, 0x32, 0x4e, 0x34, 0x66, 0xbc, 0xe3, 0x92, 0x44, 0xd8,
	0x16, 0xd4, 0x32, 0x2d, 0xb4, 0xc9, 0xf8, 0x90, 0xb2, 0x05, 0x63, 0x4f, 0xa1, 0x11, 0xa1, 0x16,
	0x52, 0x68, 0xc1, 0x27, 0xfd, 0x8d, 0x61, 0x6b, 0xd2, 0x1b, 0xad, 0xf6, 0x60, 0x64, 0xaf, 0x6e,
	0xf4, 0xaa, 0xf0, 0x0f, 0x63, 0xad, 0xf2, 0xd9, 0x2a, 0xce, 0x7a, 0x00, 0xbe, 0x42, 0xa1, 0x51,
	0xce, 0x85, 0xe6, 0x92, 0x4e, 0x6b, 0x16, 0xca, 0x81, 0xb6, 0xb6, 0x49, 0xe5, 0x95, 0x8d, 0xce,
	0x2e, 0x94, 0x03, 0xbd, 0x3e, 0x7c, 0x0a, 0x9c, 0x5e, 0x1f, 0xbe, 0x3c, 0xd0, 0xdd, 0x67, 0xd0,
	0xbe, 0x76, 0x36, 0xfb, 0x1f, 0x36, 0x3e, 0x60, 0x5e, 0x6c, 0x91, 0x85, 0xf6, 0x63, 0xcf, 0xc5,
	0xc2, 0x60, 0xb1, 0x47, 0x8e, 0xec, 0x97, 0xf7, 0x4a, 0x83, 0x3d, 0x60, 0x47, 0x87, 0x27, 0x33,
	0x14, 0xd2, 0x7e, 0xc4, 0x0c, 0x3f, 0x1a, 0xcc, 0xf4, 0x9f, 0xac, 0xe1, 0x60, 0x1f, 0xee, 0x5c,
	0xab, 0xcc, 0xd2, 0x24, 0xce, 0x90, 0x3d, 0x82, 0x8a, 0x1d, 0x0c, 0x15, 0xb7, 0x26, 0xff, 0xdd,
	0x98, 0xd2, 0x8c, 0xcc, 0xc1, 0xe7, 0x32, 0xdc, 0x7b, 0xf3, 0xfa, 0xed, 0xc9, 0x4b, 0x1a, 0xc3,
	0x2d, 0x4f, 0xfe, 0x1b, 0x0f, 0xe0, 0x9f, 0xd8, 0xee, 0xc1, 0x0b, 0xd8, 0xba, 0x39, 0xf5, 0x5b,
	0xdc, 0xda, 0xe4, 0x53, 0xc9, 0xa5, 0xd8, 0x3b, 0x68, 0x5c, 0xdd, 0x3b, 0x5b, 0x7f, 0x07, 0xdf,
	0x6f, 0x52, 0x77, 0xfb, 0x67, 0xb6, 0x3b, 0x78, 0xd0, 0x5a, 0x5e, 0xf2, 0x3a, 0x54, 0xc7, 0x0a,
	0x85, 0x64, 0xef, 0x01, 0xbe, 0xfd, 0x36, 0xd6, 0x5f, 0x2b, 0xfd, 0xe1, 0xb2, 0x74, 0x77, 0x7e,
	0x91, 0x28, 0xfa, 0xb7, 0x97, 0x97, 0xbc, 0x09, 0xf5, 0xb1, 0x7b, 0x70, 0xdd, 0xed, 0xe5, 0x45,
	0xaf, 0x03, 0x9b, 0xeb, 0xff, 0xf0, 0xcb, 0x8b, 0x5e, 0x83, 0xd5, 0xb2, 0x5d, 0x8b, 0xbd, 0x1a,
	0x35, 0x7b, 0xf2, 0x35, 0x00, 0x00, 0xff, 0xff, 0x96, 0xf3, 0x88, 0x0b, 0x23, 0x06, 0x00, 0x00,
}
