// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/lolibrary/lolibrary/service.item/proto/item.proto

package itemproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/lolibrary/lolibrary/cmd/protoc-gen-router/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Status int32

const (
	Status_DRAFT     Status = 0
	Status_PUBLISHED Status = 1
	Status_UNKNOWN   Status = 2
)

var Status_name = map[int32]string{
	0: "DRAFT",
	1: "PUBLISHED",
	2: "UNKNOWN",
}

var Status_value = map[string]int32{
	"DRAFT":     0,
	"PUBLISHED": 1,
	"UNKNOWN":   2,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3bafc3b3eeda8c31, []int{0}
}

type Item struct {
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Slug          string `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	BrandId       string `protobuf:"bytes,3,opt,name=brand_id,json=brandId,proto3" json:"brand_id,omitempty"`
	CategoryId    string `protobuf:"bytes,4,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	UserId        string `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ImageId       string `protobuf:"bytes,6,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	PublisherId   string `protobuf:"bytes,7,opt,name=publisher_id,json=publisherId,proto3" json:"publisher_id,omitempty"`
	EnglishName   string `protobuf:"bytes,8,opt,name=english_name,json=englishName,proto3" json:"english_name,omitempty"`
	ForeignName   string `protobuf:"bytes,9,opt,name=foreign_name,json=foreignName,proto3" json:"foreign_name,omitempty"`
	ProductNumber string `protobuf:"bytes,10,opt,name=product_number,json=productNumber,proto3" json:"product_number,omitempty"`
	Currency      string `protobuf:"bytes,11,opt,name=currency,proto3" json:"currency,omitempty"`
	Price         string `protobuf:"bytes,12,opt,name=price,proto3" json:"price,omitempty"`
	Year          int32  `protobuf:"varint,13,opt,name=year,proto3" json:"year,omitempty"`
	Notes         string `protobuf:"bytes,14,opt,name=notes,proto3" json:"notes,omitempty"`
	Status        Status `protobuf:"varint,40,opt,name=status,proto3,enum=itemproto.Status" json:"status,omitempty"`
	// key-value searchable metadata.
	Metadata   map[string]string `protobuf:"bytes,50,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Features   []string          `protobuf:"bytes,51,rep,name=features,proto3" json:"features,omitempty"`
	Colors     []string          `protobuf:"bytes,52,rep,name=colors,proto3" json:"colors,omitempty"`
	Tags       []string          `protobuf:"bytes,53,rep,name=tags,proto3" json:"tags,omitempty"`
	Attributes map[string]string `protobuf:"bytes,54,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// timestamps
	CreatedAt            string   `protobuf:"bytes,100,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,101,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	PublishedAt          string   `protobuf:"bytes,102,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bafc3b3eeda8c31, []int{0}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Item) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *Item) GetBrandId() string {
	if m != nil {
		return m.BrandId
	}
	return ""
}

func (m *Item) GetCategoryId() string {
	if m != nil {
		return m.CategoryId
	}
	return ""
}

func (m *Item) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Item) GetImageId() string {
	if m != nil {
		return m.ImageId
	}
	return ""
}

func (m *Item) GetPublisherId() string {
	if m != nil {
		return m.PublisherId
	}
	return ""
}

func (m *Item) GetEnglishName() string {
	if m != nil {
		return m.EnglishName
	}
	return ""
}

func (m *Item) GetForeignName() string {
	if m != nil {
		return m.ForeignName
	}
	return ""
}

func (m *Item) GetProductNumber() string {
	if m != nil {
		return m.ProductNumber
	}
	return ""
}

func (m *Item) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *Item) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *Item) GetYear() int32 {
	if m != nil {
		return m.Year
	}
	return 0
}

func (m *Item) GetNotes() string {
	if m != nil {
		return m.Notes
	}
	return ""
}

func (m *Item) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_DRAFT
}

func (m *Item) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Item) GetFeatures() []string {
	if m != nil {
		return m.Features
	}
	return nil
}

func (m *Item) GetColors() []string {
	if m != nil {
		return m.Colors
	}
	return nil
}

func (m *Item) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Item) GetAttributes() map[string]string {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *Item) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Item) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *Item) GetPublishedAt() string {
	if m != nil {
		return m.PublishedAt
	}
	return ""
}

type GETReadItemRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Slug                 string   `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GETReadItemRequest) Reset()         { *m = GETReadItemRequest{} }
func (m *GETReadItemRequest) String() string { return proto.CompactTextString(m) }
func (*GETReadItemRequest) ProtoMessage()    {}
func (*GETReadItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bafc3b3eeda8c31, []int{1}
}

func (m *GETReadItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GETReadItemRequest.Unmarshal(m, b)
}
func (m *GETReadItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GETReadItemRequest.Marshal(b, m, deterministic)
}
func (m *GETReadItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GETReadItemRequest.Merge(m, src)
}
func (m *GETReadItemRequest) XXX_Size() int {
	return xxx_messageInfo_GETReadItemRequest.Size(m)
}
func (m *GETReadItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GETReadItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GETReadItemRequest proto.InternalMessageInfo

func (m *GETReadItemRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GETReadItemRequest) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

type GETReadItemResponse struct {
	Item                 *Item    `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GETReadItemResponse) Reset()         { *m = GETReadItemResponse{} }
func (m *GETReadItemResponse) String() string { return proto.CompactTextString(m) }
func (*GETReadItemResponse) ProtoMessage()    {}
func (*GETReadItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bafc3b3eeda8c31, []int{2}
}

func (m *GETReadItemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GETReadItemResponse.Unmarshal(m, b)
}
func (m *GETReadItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GETReadItemResponse.Marshal(b, m, deterministic)
}
func (m *GETReadItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GETReadItemResponse.Merge(m, src)
}
func (m *GETReadItemResponse) XXX_Size() int {
	return xxx_messageInfo_GETReadItemResponse.Size(m)
}
func (m *GETReadItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GETReadItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GETReadItemResponse proto.InternalMessageInfo

func (m *GETReadItemResponse) GetItem() *Item {
	if m != nil {
		return m.Item
	}
	return nil
}

type POSTCreateItemRequest struct {
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Slug          string `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	BrandId       string `protobuf:"bytes,3,opt,name=brand_id,json=brandId,proto3" json:"brand_id,omitempty"`
	CategoryId    string `protobuf:"bytes,4,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	UserId        string `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ImageId       string `protobuf:"bytes,6,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	EnglishName   string `protobuf:"bytes,8,opt,name=english_name,json=englishName,proto3" json:"english_name,omitempty"`
	ForeignName   string `protobuf:"bytes,9,opt,name=foreign_name,json=foreignName,proto3" json:"foreign_name,omitempty"`
	ProductNumber string `protobuf:"bytes,10,opt,name=product_number,json=productNumber,proto3" json:"product_number,omitempty"`
	Currency      string `protobuf:"bytes,11,opt,name=currency,proto3" json:"currency,omitempty"`
	Price         string `protobuf:"bytes,12,opt,name=price,proto3" json:"price,omitempty"`
	Year          int32  `protobuf:"varint,13,opt,name=year,proto3" json:"year,omitempty"`
	Notes         string `protobuf:"bytes,14,opt,name=notes,proto3" json:"notes,omitempty"`
	// key-value searchable metadata.
	Metadata   map[string]string `protobuf:"bytes,50,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Features   []string          `protobuf:"bytes,51,rep,name=features,proto3" json:"features,omitempty"`
	Colors     []string          `protobuf:"bytes,52,rep,name=colors,proto3" json:"colors,omitempty"`
	Tags       []string          `protobuf:"bytes,53,rep,name=tags,proto3" json:"tags,omitempty"`
	Attributes map[string]string `protobuf:"bytes,54,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// timestamps
	CreatedAt            string   `protobuf:"bytes,100,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,101,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	PublishedAt          string   `protobuf:"bytes,102,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *POSTCreateItemRequest) Reset()         { *m = POSTCreateItemRequest{} }
func (m *POSTCreateItemRequest) String() string { return proto.CompactTextString(m) }
func (*POSTCreateItemRequest) ProtoMessage()    {}
func (*POSTCreateItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bafc3b3eeda8c31, []int{3}
}

func (m *POSTCreateItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_POSTCreateItemRequest.Unmarshal(m, b)
}
func (m *POSTCreateItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_POSTCreateItemRequest.Marshal(b, m, deterministic)
}
func (m *POSTCreateItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_POSTCreateItemRequest.Merge(m, src)
}
func (m *POSTCreateItemRequest) XXX_Size() int {
	return xxx_messageInfo_POSTCreateItemRequest.Size(m)
}
func (m *POSTCreateItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_POSTCreateItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_POSTCreateItemRequest proto.InternalMessageInfo

func (m *POSTCreateItemRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *POSTCreateItemRequest) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *POSTCreateItemRequest) GetBrandId() string {
	if m != nil {
		return m.BrandId
	}
	return ""
}

func (m *POSTCreateItemRequest) GetCategoryId() string {
	if m != nil {
		return m.CategoryId
	}
	return ""
}

func (m *POSTCreateItemRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *POSTCreateItemRequest) GetImageId() string {
	if m != nil {
		return m.ImageId
	}
	return ""
}

func (m *POSTCreateItemRequest) GetEnglishName() string {
	if m != nil {
		return m.EnglishName
	}
	return ""
}

func (m *POSTCreateItemRequest) GetForeignName() string {
	if m != nil {
		return m.ForeignName
	}
	return ""
}

func (m *POSTCreateItemRequest) GetProductNumber() string {
	if m != nil {
		return m.ProductNumber
	}
	return ""
}

func (m *POSTCreateItemRequest) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *POSTCreateItemRequest) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *POSTCreateItemRequest) GetYear() int32 {
	if m != nil {
		return m.Year
	}
	return 0
}

func (m *POSTCreateItemRequest) GetNotes() string {
	if m != nil {
		return m.Notes
	}
	return ""
}

func (m *POSTCreateItemRequest) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *POSTCreateItemRequest) GetFeatures() []string {
	if m != nil {
		return m.Features
	}
	return nil
}

func (m *POSTCreateItemRequest) GetColors() []string {
	if m != nil {
		return m.Colors
	}
	return nil
}

func (m *POSTCreateItemRequest) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *POSTCreateItemRequest) GetAttributes() map[string]string {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *POSTCreateItemRequest) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *POSTCreateItemRequest) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *POSTCreateItemRequest) GetPublishedAt() string {
	if m != nil {
		return m.PublishedAt
	}
	return ""
}

type POSTCreateItemResponse struct {
	Item                 *Item    `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *POSTCreateItemResponse) Reset()         { *m = POSTCreateItemResponse{} }
func (m *POSTCreateItemResponse) String() string { return proto.CompactTextString(m) }
func (*POSTCreateItemResponse) ProtoMessage()    {}
func (*POSTCreateItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bafc3b3eeda8c31, []int{4}
}

func (m *POSTCreateItemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_POSTCreateItemResponse.Unmarshal(m, b)
}
func (m *POSTCreateItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_POSTCreateItemResponse.Marshal(b, m, deterministic)
}
func (m *POSTCreateItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_POSTCreateItemResponse.Merge(m, src)
}
func (m *POSTCreateItemResponse) XXX_Size() int {
	return xxx_messageInfo_POSTCreateItemResponse.Size(m)
}
func (m *POSTCreateItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_POSTCreateItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_POSTCreateItemResponse proto.InternalMessageInfo

func (m *POSTCreateItemResponse) GetItem() *Item {
	if m != nil {
		return m.Item
	}
	return nil
}

type PUTUpdateItemRequest struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Slug                 string            `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	BrandId              string            `protobuf:"bytes,3,opt,name=brand_id,json=brandId,proto3" json:"brand_id,omitempty"`
	CategoryId           string            `protobuf:"bytes,4,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	ImageId              string            `protobuf:"bytes,6,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	EnglishName          string            `protobuf:"bytes,8,opt,name=english_name,json=englishName,proto3" json:"english_name,omitempty"`
	ForeignName          string            `protobuf:"bytes,9,opt,name=foreign_name,json=foreignName,proto3" json:"foreign_name,omitempty"`
	ProductNumber        string            `protobuf:"bytes,10,opt,name=product_number,json=productNumber,proto3" json:"product_number,omitempty"`
	Currency             string            `protobuf:"bytes,11,opt,name=currency,proto3" json:"currency,omitempty"`
	Price                string            `protobuf:"bytes,12,opt,name=price,proto3" json:"price,omitempty"`
	Year                 int32             `protobuf:"varint,13,opt,name=year,proto3" json:"year,omitempty"`
	Notes                string            `protobuf:"bytes,14,opt,name=notes,proto3" json:"notes,omitempty"`
	Metadata             map[string]string `protobuf:"bytes,50,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PUTUpdateItemRequest) Reset()         { *m = PUTUpdateItemRequest{} }
func (m *PUTUpdateItemRequest) String() string { return proto.CompactTextString(m) }
func (*PUTUpdateItemRequest) ProtoMessage()    {}
func (*PUTUpdateItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bafc3b3eeda8c31, []int{5}
}

func (m *PUTUpdateItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PUTUpdateItemRequest.Unmarshal(m, b)
}
func (m *PUTUpdateItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PUTUpdateItemRequest.Marshal(b, m, deterministic)
}
func (m *PUTUpdateItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PUTUpdateItemRequest.Merge(m, src)
}
func (m *PUTUpdateItemRequest) XXX_Size() int {
	return xxx_messageInfo_PUTUpdateItemRequest.Size(m)
}
func (m *PUTUpdateItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PUTUpdateItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PUTUpdateItemRequest proto.InternalMessageInfo

func (m *PUTUpdateItemRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PUTUpdateItemRequest) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *PUTUpdateItemRequest) GetBrandId() string {
	if m != nil {
		return m.BrandId
	}
	return ""
}

func (m *PUTUpdateItemRequest) GetCategoryId() string {
	if m != nil {
		return m.CategoryId
	}
	return ""
}

func (m *PUTUpdateItemRequest) GetImageId() string {
	if m != nil {
		return m.ImageId
	}
	return ""
}

func (m *PUTUpdateItemRequest) GetEnglishName() string {
	if m != nil {
		return m.EnglishName
	}
	return ""
}

func (m *PUTUpdateItemRequest) GetForeignName() string {
	if m != nil {
		return m.ForeignName
	}
	return ""
}

func (m *PUTUpdateItemRequest) GetProductNumber() string {
	if m != nil {
		return m.ProductNumber
	}
	return ""
}

func (m *PUTUpdateItemRequest) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *PUTUpdateItemRequest) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *PUTUpdateItemRequest) GetYear() int32 {
	if m != nil {
		return m.Year
	}
	return 0
}

func (m *PUTUpdateItemRequest) GetNotes() string {
	if m != nil {
		return m.Notes
	}
	return ""
}

func (m *PUTUpdateItemRequest) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type PUTUpdateItemResponse struct {
	Item                 *Item    `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PUTUpdateItemResponse) Reset()         { *m = PUTUpdateItemResponse{} }
func (m *PUTUpdateItemResponse) String() string { return proto.CompactTextString(m) }
func (*PUTUpdateItemResponse) ProtoMessage()    {}
func (*PUTUpdateItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bafc3b3eeda8c31, []int{6}
}

func (m *PUTUpdateItemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PUTUpdateItemResponse.Unmarshal(m, b)
}
func (m *PUTUpdateItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PUTUpdateItemResponse.Marshal(b, m, deterministic)
}
func (m *PUTUpdateItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PUTUpdateItemResponse.Merge(m, src)
}
func (m *PUTUpdateItemResponse) XXX_Size() int {
	return xxx_messageInfo_PUTUpdateItemResponse.Size(m)
}
func (m *PUTUpdateItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PUTUpdateItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PUTUpdateItemResponse proto.InternalMessageInfo

func (m *PUTUpdateItemResponse) GetItem() *Item {
	if m != nil {
		return m.Item
	}
	return nil
}

func init() {
	proto.RegisterEnum("itemproto.Status", Status_name, Status_value)
	proto.RegisterType((*Item)(nil), "itemproto.Item")
	proto.RegisterMapType((map[string]string)(nil), "itemproto.Item.AttributesEntry")
	proto.RegisterMapType((map[string]string)(nil), "itemproto.Item.MetadataEntry")
	proto.RegisterType((*GETReadItemRequest)(nil), "itemproto.GETReadItemRequest")
	proto.RegisterType((*GETReadItemResponse)(nil), "itemproto.GETReadItemResponse")
	proto.RegisterType((*POSTCreateItemRequest)(nil), "itemproto.POSTCreateItemRequest")
	proto.RegisterMapType((map[string]string)(nil), "itemproto.POSTCreateItemRequest.AttributesEntry")
	proto.RegisterMapType((map[string]string)(nil), "itemproto.POSTCreateItemRequest.MetadataEntry")
	proto.RegisterType((*POSTCreateItemResponse)(nil), "itemproto.POSTCreateItemResponse")
	proto.RegisterType((*PUTUpdateItemRequest)(nil), "itemproto.PUTUpdateItemRequest")
	proto.RegisterMapType((map[string]string)(nil), "itemproto.PUTUpdateItemRequest.MetadataEntry")
	proto.RegisterType((*PUTUpdateItemResponse)(nil), "itemproto.PUTUpdateItemResponse")
}

func init() {
	proto.RegisterFile("github.com/lolibrary/lolibrary/service.item/proto/item.proto", fileDescriptor_3bafc3b3eeda8c31)
}

var fileDescriptor_3bafc3b3eeda8c31 = []byte{
	// 825 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe4, 0x56, 0xef, 0x8e, 0x22, 0x45,
	0x10, 0x97, 0x7f, 0x03, 0x14, 0x0b, 0x87, 0xed, 0xdd, 0xd9, 0x4e, 0xc2, 0x2d, 0x87, 0x31, 0x41,
	0x13, 0xc0, 0x70, 0x6a, 0xce, 0xf3, 0x2e, 0x06, 0xdd, 0x75, 0xc5, 0x3f, 0x2c, 0x99, 0x05, 0xfd,
	0x26, 0x36, 0xd3, 0xbd, 0xb3, 0x13, 0x99, 0x19, 0xec, 0xe9, 0xd9, 0x84, 0xaf, 0x3c, 0xcc, 0xbe,
	0xc1, 0xc6, 0xaf, 0x3e, 0x83, 0x8f, 0xe0, 0x93, 0x98, 0xee, 0x1e, 0xd8, 0x59, 0x76, 0x57, 0x24,
	0x46, 0x4d, 0xdc, 0x6f, 0x55, 0xf5, 0xfb, 0x75, 0x51, 0x5d, 0x55, 0xbf, 0x69, 0xe0, 0xa5, 0xe3,
	0x8a, 0xb3, 0x68, 0xda, 0xb6, 0x03, 0xaf, 0x33, 0x0b, 0x66, 0xee, 0x94, 0x13, 0xbe, 0x48, 0x58,
	0x21, 0xe3, 0xe7, 0xae, 0xcd, 0xda, 0xae, 0x60, 0x5e, 0x67, 0xce, 0x03, 0x11, 0x74, 0xa4, 0xd9,
	0x56, 0x26, 0x2a, 0x4a, 0x5b, 0x99, 0xe6, 0xd1, 0x96, 0x44, 0xb6, 0x47, 0xf5, 0x79, 0xbb, 0xe5,
	0x30, 0xbf, 0xc5, 0x83, 0x48, 0x30, 0x1e, 0x67, 0xd4, 0x8e, 0xce, 0xd9, 0xf8, 0xcd, 0x80, 0x6c,
	0x5f, 0x30, 0x0f, 0x55, 0x20, 0xed, 0x52, 0x9c, 0xaa, 0xa7, 0x9a, 0x45, 0x2b, 0xed, 0x52, 0x84,
	0x20, 0x1b, 0xce, 0x22, 0x07, 0xa7, 0x55, 0x44, 0xd9, 0xe8, 0x2d, 0x28, 0x4c, 0x39, 0xf1, 0xe9,
	0xc4, 0xa5, 0x38, 0xa3, 0xe2, 0x79, 0xe5, 0xf7, 0x29, 0xda, 0x87, 0x92, 0x4d, 0x04, 0x73, 0x02,
	0xbe, 0x90, 0x68, 0x56, 0xa1, 0xb0, 0x0a, 0xf5, 0x29, 0x7a, 0x13, 0xf2, 0x51, 0xc8, 0xb8, 0x04,
	0x73, 0x0a, 0x34, 0xa4, 0xdb, 0xa7, 0x32, 0xa9, 0xeb, 0x11, 0x87, 0x49, 0xc4, 0xd0, 0x49, 0x95,
	0xdf, 0xa7, 0xe8, 0x29, 0xec, 0xcd, 0xa3, 0xe9, 0xcc, 0x0d, 0xcf, 0xf4, 0xc1, 0xbc, 0x82, 0x4b,
	0xeb, 0x98, 0xa6, 0x30, 0xdf, 0x91, 0xee, 0xc4, 0x27, 0x1e, 0xc3, 0x05, 0x4d, 0x89, 0x63, 0x03,
	0xe2, 0x31, 0x49, 0x39, 0x0d, 0x38, 0x73, 0x1d, 0x5f, 0x53, 0x8a, 0x9a, 0x12, 0xc7, 0x14, 0xe5,
	0x1d, 0xa8, 0xcc, 0x79, 0x40, 0x23, 0x5b, 0x4c, 0xfc, 0xc8, 0x9b, 0x32, 0x8e, 0x41, 0x91, 0xca,
	0x71, 0x74, 0xa0, 0x82, 0xc8, 0x84, 0x82, 0x1d, 0x71, 0xce, 0x7c, 0x7b, 0x81, 0x4b, 0x8a, 0xb0,
	0xf6, 0xd1, 0x43, 0xc8, 0xcd, 0xb9, 0x6b, 0x33, 0xbc, 0xa7, 0x00, 0xed, 0xc8, 0x2e, 0x2e, 0x18,
	0xe1, 0xb8, 0x5c, 0x4f, 0x35, 0x73, 0x96, 0xb2, 0x25, 0xd3, 0x0f, 0x04, 0x0b, 0x71, 0x45, 0x33,
	0x95, 0x83, 0xde, 0x05, 0x23, 0x14, 0x44, 0x44, 0x21, 0x6e, 0xd6, 0x53, 0xcd, 0x4a, 0xf7, 0xf5,
	0xf6, 0x7a, 0xda, 0xed, 0x13, 0x05, 0x58, 0x31, 0x01, 0x7d, 0x0c, 0x05, 0x8f, 0x09, 0x42, 0x89,
	0x20, 0xb8, 0x5b, 0xcf, 0x34, 0x4b, 0xdd, 0x5a, 0x82, 0x2c, 0xa7, 0xd9, 0xfe, 0x36, 0xc6, 0x0f,
	0x7d, 0xc1, 0x17, 0xd6, 0x9a, 0x2e, 0x6f, 0x70, 0xca, 0x88, 0x88, 0x38, 0x0b, 0xf1, 0xb3, 0x7a,
	0x46, 0xde, 0x60, 0xe5, 0xa3, 0xc7, 0x60, 0xd8, 0xc1, 0x2c, 0xe0, 0x21, 0xfe, 0x40, 0x21, 0xb1,
	0x27, 0xef, 0x20, 0x88, 0x13, 0xe2, 0x0f, 0x55, 0x54, 0xd9, 0xe8, 0x53, 0x00, 0x22, 0x04, 0x77,
	0xa7, 0x91, 0xbc, 0xc8, 0x47, 0xaa, 0x88, 0xfd, 0xcd, 0x22, 0x7a, 0x6b, 0x86, 0x2e, 0x23, 0x71,
	0x04, 0xd5, 0x00, 0x6c, 0xce, 0x88, 0x60, 0x74, 0x42, 0x04, 0xa6, 0xaa, 0x13, 0xc5, 0x38, 0xd2,
	0x13, 0x12, 0x8e, 0xe6, 0x74, 0x05, 0x33, 0x0d, 0xc7, 0x91, 0x9e, 0x48, 0x2e, 0x86, 0x22, 0x9c,
	0x5e, 0x5f, 0x0c, 0xda, 0x13, 0xe6, 0x27, 0x50, 0xbe, 0xd6, 0x04, 0x54, 0x85, 0xcc, 0x4f, 0x6c,
	0x11, 0x6f, 0xb8, 0x34, 0xe5, 0x20, 0xce, 0xc9, 0x2c, 0x62, 0xf1, 0x8e, 0x6b, 0xe7, 0x45, 0xfa,
	0x79, 0xca, 0x7c, 0x05, 0x0f, 0x36, 0x8a, 0xdf, 0xe5, 0x78, 0xe3, 0x39, 0xa0, 0xa3, 0xc3, 0x91,
	0xc5, 0x08, 0x95, 0x7d, 0xb0, 0xd8, 0xcf, 0x11, 0x0b, 0xc5, 0x5f, 0x51, 0x58, 0xe3, 0x05, 0xbc,
	0x71, 0xed, 0x64, 0x38, 0x0f, 0xfc, 0x90, 0xa1, 0xb7, 0x21, 0x2b, 0x7b, 0xab, 0x0e, 0x97, 0xba,
	0x0f, 0x36, 0x1a, 0x6d, 0x29, 0xb0, 0xf1, 0x8b, 0x01, 0x8f, 0x86, 0xc7, 0x27, 0xa3, 0xcf, 0x55,
	0x17, 0x77, 0xfc, 0xe5, 0xff, 0x42, 0xdb, 0xff, 0x0f, 0xe1, 0x7e, 0x75, 0x43, 0x8d, 0xed, 0xc4,
	0x7c, 0x6e, 0x1d, 0xc8, 0x3f, 0x2e, 0xcf, 0xe1, 0x2d, 0xf2, 0x7c, 0x7f, 0x6b, 0x55, 0xf7, 0x56,
	0xaf, 0xaf, 0xe0, 0xf1, 0x66, 0x47, 0x76, 0x11, 0xde, 0xef, 0x19, 0x78, 0x38, 0x1c, 0x8f, 0xc6,
	0xea, 0xba, 0xff, 0xa6, 0xee, 0xee, 0x83, 0xbc, 0xfa, 0x37, 0xe4, 0xd5, 0x4a, 0x2e, 0xf2, 0x2d,
	0x6d, 0xbf, 0x4b, 0x5d, 0x7f, 0x6b, 0xc5, 0x1a, 0x2f, 0xe1, 0xd1, 0xc6, 0x8f, 0xed, 0xb0, 0x22,
	0xef, 0x75, 0xc0, 0xd0, 0x8f, 0x38, 0x2a, 0x42, 0xee, 0xc0, 0xea, 0x7d, 0x31, 0xaa, 0xbe, 0x86,
	0xca, 0x50, 0x1c, 0x8e, 0x3f, 0xfb, 0xa6, 0x7f, 0xf2, 0xe5, 0xe1, 0x41, 0x35, 0x85, 0x4a, 0x90,
	0x1f, 0x0f, 0xbe, 0x1e, 0x1c, 0x7f, 0x3f, 0xa8, 0xa6, 0xbb, 0xbf, 0xa6, 0x75, 0x5a, 0xf4, 0x1d,
	0x14, 0x56, 0xcf, 0x01, 0x4a, 0x3e, 0xf3, 0x37, 0x1f, 0x18, 0xf3, 0xc9, 0x5d, 0xb0, 0xae, 0xb4,
	0x51, 0x5a, 0x5e, 0xe2, 0x3c, 0xe4, 0x3a, 0x9c, 0x11, 0x8a, 0x7e, 0x04, 0xb8, 0xda, 0x77, 0x54,
	0xdf, 0xf6, 0x71, 0x30, 0x9f, 0xfe, 0x09, 0x23, 0xce, 0x5f, 0x5e, 0x5e, 0xe2, 0x22, 0xe4, 0x3b,
	0xfa, 0xb3, 0x80, 0x7e, 0x00, 0xb8, 0x6a, 0x17, 0xda, 0xdf, 0x32, 0x35, 0xb3, 0x7e, 0x37, 0x61,
	0x23, 0xbf, 0xfe, 0xae, 0x98, 0x4f, 0x96, 0x17, 0xb5, 0x0a, 0xec, 0x25, 0xff, 0x33, 0x2f, 0x2f,
	0x6a, 0x05, 0x64, 0x84, 0x2d, 0x69, 0x4f, 0x0d, 0x95, 0xeb, 0xd9, 0x1f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0xa8, 0xfb, 0xa7, 0x35, 0x75, 0x0b, 0x00, 0x00,
}
