// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/lolibrary/lolibrary/service.tag/proto/tag.proto

package tagproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/lolibrary/lolibrary/cmd/protoc-gen-router/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Tag struct {
	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Slug string `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	Name string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	// timestamps
	CreatedAt            string   `protobuf:"bytes,100,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,101,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tag) Reset()         { *m = Tag{} }
func (m *Tag) String() string { return proto.CompactTextString(m) }
func (*Tag) ProtoMessage()    {}
func (*Tag) Descriptor() ([]byte, []int) {
	return fileDescriptor_634d63a7ecfea76f, []int{0}
}

func (m *Tag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tag.Unmarshal(m, b)
}
func (m *Tag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tag.Marshal(b, m, deterministic)
}
func (m *Tag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tag.Merge(m, src)
}
func (m *Tag) XXX_Size() int {
	return xxx_messageInfo_Tag.Size(m)
}
func (m *Tag) XXX_DiscardUnknown() {
	xxx_messageInfo_Tag.DiscardUnknown(m)
}

var xxx_messageInfo_Tag proto.InternalMessageInfo

func (m *Tag) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Tag) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *Tag) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Tag) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Tag) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type GETReadTagRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Slug                 string   `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GETReadTagRequest) Reset()         { *m = GETReadTagRequest{} }
func (m *GETReadTagRequest) String() string { return proto.CompactTextString(m) }
func (*GETReadTagRequest) ProtoMessage()    {}
func (*GETReadTagRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_634d63a7ecfea76f, []int{1}
}

func (m *GETReadTagRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GETReadTagRequest.Unmarshal(m, b)
}
func (m *GETReadTagRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GETReadTagRequest.Marshal(b, m, deterministic)
}
func (m *GETReadTagRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GETReadTagRequest.Merge(m, src)
}
func (m *GETReadTagRequest) XXX_Size() int {
	return xxx_messageInfo_GETReadTagRequest.Size(m)
}
func (m *GETReadTagRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GETReadTagRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GETReadTagRequest proto.InternalMessageInfo

func (m *GETReadTagRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GETReadTagRequest) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

type GETReadTagResponse struct {
	Tag                  *Tag     `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GETReadTagResponse) Reset()         { *m = GETReadTagResponse{} }
func (m *GETReadTagResponse) String() string { return proto.CompactTextString(m) }
func (*GETReadTagResponse) ProtoMessage()    {}
func (*GETReadTagResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_634d63a7ecfea76f, []int{2}
}

func (m *GETReadTagResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GETReadTagResponse.Unmarshal(m, b)
}
func (m *GETReadTagResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GETReadTagResponse.Marshal(b, m, deterministic)
}
func (m *GETReadTagResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GETReadTagResponse.Merge(m, src)
}
func (m *GETReadTagResponse) XXX_Size() int {
	return xxx_messageInfo_GETReadTagResponse.Size(m)
}
func (m *GETReadTagResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GETReadTagResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GETReadTagResponse proto.InternalMessageInfo

func (m *GETReadTagResponse) GetTag() *Tag {
	if m != nil {
		return m.Tag
	}
	return nil
}

type GETListTagsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GETListTagsRequest) Reset()         { *m = GETListTagsRequest{} }
func (m *GETListTagsRequest) String() string { return proto.CompactTextString(m) }
func (*GETListTagsRequest) ProtoMessage()    {}
func (*GETListTagsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_634d63a7ecfea76f, []int{3}
}

func (m *GETListTagsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GETListTagsRequest.Unmarshal(m, b)
}
func (m *GETListTagsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GETListTagsRequest.Marshal(b, m, deterministic)
}
func (m *GETListTagsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GETListTagsRequest.Merge(m, src)
}
func (m *GETListTagsRequest) XXX_Size() int {
	return xxx_messageInfo_GETListTagsRequest.Size(m)
}
func (m *GETListTagsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GETListTagsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GETListTagsRequest proto.InternalMessageInfo

type GETListTagsResponse struct {
	Tags                 []*Tag   `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GETListTagsResponse) Reset()         { *m = GETListTagsResponse{} }
func (m *GETListTagsResponse) String() string { return proto.CompactTextString(m) }
func (*GETListTagsResponse) ProtoMessage()    {}
func (*GETListTagsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_634d63a7ecfea76f, []int{4}
}

func (m *GETListTagsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GETListTagsResponse.Unmarshal(m, b)
}
func (m *GETListTagsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GETListTagsResponse.Marshal(b, m, deterministic)
}
func (m *GETListTagsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GETListTagsResponse.Merge(m, src)
}
func (m *GETListTagsResponse) XXX_Size() int {
	return xxx_messageInfo_GETListTagsResponse.Size(m)
}
func (m *GETListTagsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GETListTagsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GETListTagsResponse proto.InternalMessageInfo

func (m *GETListTagsResponse) GetTags() []*Tag {
	if m != nil {
		return m.Tags
	}
	return nil
}

type POSTCreateTagRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Slug                 string   `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *POSTCreateTagRequest) Reset()         { *m = POSTCreateTagRequest{} }
func (m *POSTCreateTagRequest) String() string { return proto.CompactTextString(m) }
func (*POSTCreateTagRequest) ProtoMessage()    {}
func (*POSTCreateTagRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_634d63a7ecfea76f, []int{5}
}

func (m *POSTCreateTagRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_POSTCreateTagRequest.Unmarshal(m, b)
}
func (m *POSTCreateTagRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_POSTCreateTagRequest.Marshal(b, m, deterministic)
}
func (m *POSTCreateTagRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_POSTCreateTagRequest.Merge(m, src)
}
func (m *POSTCreateTagRequest) XXX_Size() int {
	return xxx_messageInfo_POSTCreateTagRequest.Size(m)
}
func (m *POSTCreateTagRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_POSTCreateTagRequest.DiscardUnknown(m)
}

var xxx_messageInfo_POSTCreateTagRequest proto.InternalMessageInfo

func (m *POSTCreateTagRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *POSTCreateTagRequest) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *POSTCreateTagRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type POSTCreateTagResponse struct {
	Tag                  *Tag     `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *POSTCreateTagResponse) Reset()         { *m = POSTCreateTagResponse{} }
func (m *POSTCreateTagResponse) String() string { return proto.CompactTextString(m) }
func (*POSTCreateTagResponse) ProtoMessage()    {}
func (*POSTCreateTagResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_634d63a7ecfea76f, []int{6}
}

func (m *POSTCreateTagResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_POSTCreateTagResponse.Unmarshal(m, b)
}
func (m *POSTCreateTagResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_POSTCreateTagResponse.Marshal(b, m, deterministic)
}
func (m *POSTCreateTagResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_POSTCreateTagResponse.Merge(m, src)
}
func (m *POSTCreateTagResponse) XXX_Size() int {
	return xxx_messageInfo_POSTCreateTagResponse.Size(m)
}
func (m *POSTCreateTagResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_POSTCreateTagResponse.DiscardUnknown(m)
}

var xxx_messageInfo_POSTCreateTagResponse proto.InternalMessageInfo

func (m *POSTCreateTagResponse) GetTag() *Tag {
	if m != nil {
		return m.Tag
	}
	return nil
}

type PUTUpdateTagRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Slug                 string   `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PUTUpdateTagRequest) Reset()         { *m = PUTUpdateTagRequest{} }
func (m *PUTUpdateTagRequest) String() string { return proto.CompactTextString(m) }
func (*PUTUpdateTagRequest) ProtoMessage()    {}
func (*PUTUpdateTagRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_634d63a7ecfea76f, []int{7}
}

func (m *PUTUpdateTagRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PUTUpdateTagRequest.Unmarshal(m, b)
}
func (m *PUTUpdateTagRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PUTUpdateTagRequest.Marshal(b, m, deterministic)
}
func (m *PUTUpdateTagRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PUTUpdateTagRequest.Merge(m, src)
}
func (m *PUTUpdateTagRequest) XXX_Size() int {
	return xxx_messageInfo_PUTUpdateTagRequest.Size(m)
}
func (m *PUTUpdateTagRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PUTUpdateTagRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PUTUpdateTagRequest proto.InternalMessageInfo

func (m *PUTUpdateTagRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PUTUpdateTagRequest) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *PUTUpdateTagRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type PUTUpdateTagResponse struct {
	Tag                  *Tag     `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PUTUpdateTagResponse) Reset()         { *m = PUTUpdateTagResponse{} }
func (m *PUTUpdateTagResponse) String() string { return proto.CompactTextString(m) }
func (*PUTUpdateTagResponse) ProtoMessage()    {}
func (*PUTUpdateTagResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_634d63a7ecfea76f, []int{8}
}

func (m *PUTUpdateTagResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PUTUpdateTagResponse.Unmarshal(m, b)
}
func (m *PUTUpdateTagResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PUTUpdateTagResponse.Marshal(b, m, deterministic)
}
func (m *PUTUpdateTagResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PUTUpdateTagResponse.Merge(m, src)
}
func (m *PUTUpdateTagResponse) XXX_Size() int {
	return xxx_messageInfo_PUTUpdateTagResponse.Size(m)
}
func (m *PUTUpdateTagResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PUTUpdateTagResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PUTUpdateTagResponse proto.InternalMessageInfo

func (m *PUTUpdateTagResponse) GetTag() *Tag {
	if m != nil {
		return m.Tag
	}
	return nil
}

type DELETERemoveTagRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DELETERemoveTagRequest) Reset()         { *m = DELETERemoveTagRequest{} }
func (m *DELETERemoveTagRequest) String() string { return proto.CompactTextString(m) }
func (*DELETERemoveTagRequest) ProtoMessage()    {}
func (*DELETERemoveTagRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_634d63a7ecfea76f, []int{9}
}

func (m *DELETERemoveTagRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DELETERemoveTagRequest.Unmarshal(m, b)
}
func (m *DELETERemoveTagRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DELETERemoveTagRequest.Marshal(b, m, deterministic)
}
func (m *DELETERemoveTagRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DELETERemoveTagRequest.Merge(m, src)
}
func (m *DELETERemoveTagRequest) XXX_Size() int {
	return xxx_messageInfo_DELETERemoveTagRequest.Size(m)
}
func (m *DELETERemoveTagRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DELETERemoveTagRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DELETERemoveTagRequest proto.InternalMessageInfo

func (m *DELETERemoveTagRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DELETERemoveTagResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DELETERemoveTagResponse) Reset()         { *m = DELETERemoveTagResponse{} }
func (m *DELETERemoveTagResponse) String() string { return proto.CompactTextString(m) }
func (*DELETERemoveTagResponse) ProtoMessage()    {}
func (*DELETERemoveTagResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_634d63a7ecfea76f, []int{10}
}

func (m *DELETERemoveTagResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DELETERemoveTagResponse.Unmarshal(m, b)
}
func (m *DELETERemoveTagResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DELETERemoveTagResponse.Marshal(b, m, deterministic)
}
func (m *DELETERemoveTagResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DELETERemoveTagResponse.Merge(m, src)
}
func (m *DELETERemoveTagResponse) XXX_Size() int {
	return xxx_messageInfo_DELETERemoveTagResponse.Size(m)
}
func (m *DELETERemoveTagResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DELETERemoveTagResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DELETERemoveTagResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Tag)(nil), "tagproto.Tag")
	proto.RegisterType((*GETReadTagRequest)(nil), "tagproto.GETReadTagRequest")
	proto.RegisterType((*GETReadTagResponse)(nil), "tagproto.GETReadTagResponse")
	proto.RegisterType((*GETListTagsRequest)(nil), "tagproto.GETListTagsRequest")
	proto.RegisterType((*GETListTagsResponse)(nil), "tagproto.GETListTagsResponse")
	proto.RegisterType((*POSTCreateTagRequest)(nil), "tagproto.POSTCreateTagRequest")
	proto.RegisterType((*POSTCreateTagResponse)(nil), "tagproto.POSTCreateTagResponse")
	proto.RegisterType((*PUTUpdateTagRequest)(nil), "tagproto.PUTUpdateTagRequest")
	proto.RegisterType((*PUTUpdateTagResponse)(nil), "tagproto.PUTUpdateTagResponse")
	proto.RegisterType((*DELETERemoveTagRequest)(nil), "tagproto.DELETERemoveTagRequest")
	proto.RegisterType((*DELETERemoveTagResponse)(nil), "tagproto.DELETERemoveTagResponse")
}

func init() {
	proto.RegisterFile("github.com/lolibrary/lolibrary/service.tag/proto/tag.proto", fileDescriptor_634d63a7ecfea76f)
}

var fileDescriptor_634d63a7ecfea76f = []byte{
	// 495 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x56, 0xe3, 0x94, 0xd4, 0x13, 0x05, 0x89, 0x69, 0x00, 0x63, 0x30, 0x4d, 0xf7, 0xd4, 0x4b,
	0x6c, 0xa9, 0x08, 0xb5, 0xe2, 0x56, 0xd1, 0xa8, 0x97, 0x02, 0x25, 0xb8, 0x07, 0xc4, 0xa1, 0xda,
	0x78, 0x57, 0x8b, 0x25, 0x27, 0x0e, 0xde, 0x75, 0x25, 0xc4, 0x2d, 0x0f, 0xd3, 0x37, 0xe8, 0x23,
	0xf1, 0x1e, 0xc8, 0xbb, 0xce, 0x9f, 0x93, 0x94, 0x20, 0x71, 0x1b, 0xcf, 0xb7, 0xdf, 0x37, 0x33,
	0xdf, 0xce, 0x1a, 0xde, 0x89, 0x58, 0x7d, 0xcf, 0x07, 0x7e, 0x94, 0x0e, 0x83, 0x24, 0x4d, 0xe2,
	0x41, 0x46, 0xb3, 0x9f, 0x0b, 0x91, 0xe4, 0xd9, 0x6d, 0x1c, 0x71, 0x5f, 0x51, 0x11, 0x8c, 0xb3,
	0x54, 0xa5, 0x81, 0xa2, 0xc2, 0xd7, 0x11, 0xee, 0x29, 0x2a, 0x74, 0xe4, 0x5e, 0xfc, 0x45, 0x25,
	0x1a, 0x32, 0xc3, 0x8e, 0xba, 0x82, 0x8f, 0xba, 0x59, 0x9a, 0x2b, 0x9e, 0x95, 0x7a, 0xe6, 0xc3,
	0x48, 0x92, 0x5f, 0x60, 0x85, 0x54, 0xe0, 0x63, 0xa8, 0xc5, 0xcc, 0xd9, 0xe9, 0xec, 0x1c, 0xd9,
	0xfd, 0x5a, 0xcc, 0x10, 0xa1, 0x2e, 0x93, 0x5c, 0x38, 0x35, 0x9d, 0xd1, 0x71, 0x91, 0x1b, 0xd1,
	0x21, 0x77, 0xea, 0x26, 0x57, 0xc4, 0xe8, 0x01, 0x44, 0x19, 0xa7, 0x8a, 0xb3, 0x1b, 0xaa, 0x1c,
	0xa6, 0x11, 0xbb, 0xcc, 0x9c, 0xa9, 0x02, 0xce, 0xc7, 0x6c, 0x0a, 0x73, 0x03, 0x97, 0x99, 0x33,
	0x45, 0x4e, 0xe0, 0xc9, 0x45, 0x2f, 0xec, 0x73, 0xca, 0x42, 0x2a, 0xfa, 0xfc, 0x47, 0xce, 0xa5,
	0xda, 0xa6, 0x15, 0xf2, 0x16, 0x70, 0x91, 0x28, 0xc7, 0xe9, 0x48, 0x72, 0x3c, 0x00, 0x4b, 0x51,
	0xa1, 0xa9, 0xcd, 0xe3, 0x96, 0x3f, 0x35, 0xcb, 0x2f, 0xce, 0x14, 0x08, 0x69, 0x6b, 0xda, 0x65,
	0x2c, 0x55, 0x48, 0x85, 0x2c, 0x0b, 0x92, 0x53, 0xd8, 0x5f, 0xca, 0x96, 0x6a, 0x87, 0x50, 0x57,
	0x54, 0x48, 0x67, 0xa7, 0x63, 0xad, 0xca, 0x69, 0x88, 0x7c, 0x84, 0xf6, 0xd5, 0xa7, 0x2f, 0xe1,
	0x7b, 0x3d, 0xef, 0xbf, 0x8d, 0x30, 0x73, 0xd3, 0x9a, 0xbb, 0x49, 0x4e, 0xe1, 0x69, 0x45, 0x6f,
	0xdb, 0xc9, 0x3e, 0xc0, 0xfe, 0xd5, 0x75, 0x78, 0xad, 0x9d, 0xfd, 0x0f, 0x8d, 0x9c, 0x40, 0x7b,
	0x59, 0x6e, 0xdb, 0x3e, 0x8e, 0xe0, 0xd9, 0x79, 0xef, 0xb2, 0x17, 0xf6, 0xfa, 0x7c, 0x98, 0xde,
	0x3e, 0xd0, 0x0a, 0x79, 0x01, 0xcf, 0x57, 0x4e, 0x9a, 0x2a, 0xc7, 0xbf, 0x2d, 0x5d, 0x06, 0x3f,
	0x43, 0xa3, 0xbc, 0x62, 0x7c, 0x39, 0xaf, 0xb5, 0xb2, 0x31, 0xee, 0xab, 0xf5, 0xa0, 0x51, 0x23,
	0xcd, 0xc9, 0xbd, 0xd3, 0x80, 0xdd, 0x20, 0xe3, 0x94, 0xe1, 0x57, 0xb0, 0x67, 0x53, 0xa1, 0x37,
	0xe7, 0xad, 0x31, 0xcf, 0x7d, 0xbd, 0x09, 0x2e, 0x85, 0x5b, 0x93, 0x7b, 0xc7, 0x86, 0x46, 0x60,
	0xf6, 0x19, 0x6f, 0xc0, 0x3e, 0xe7, 0x09, 0x37, 0xd2, 0x9d, 0x39, 0x77, 0xbd, 0x1f, 0xee, 0xe1,
	0x03, 0x27, 0x2a, 0x05, 0x98, 0x96, 0xc5, 0x6f, 0x60, 0xcf, 0x36, 0x03, 0x17, 0x9b, 0x5b, 0xb3,
	0x82, 0xee, 0xc1, 0x46, 0xbc, 0x22, 0x6e, 0x1e, 0x2b, 0x86, 0xb0, 0x37, 0x7d, 0x01, 0xb8, 0xec,
	0x67, 0xe5, 0xb9, 0xb8, 0xde, 0x06, 0xb4, 0x62, 0x77, 0x12, 0x17, 0x37, 0x33, 0xb9, 0xf3, 0x5a,
	0xd0, 0x5c, 0xf8, 0xa7, 0x4d, 0xee, 0xbc, 0x06, 0xee, 0xca, 0xae, 0xa2, 0x62, 0xf0, 0x48, 0xab,
	0xbc, 0xf9, 0x13, 0x00, 0x00, 0xff, 0xff, 0xf9, 0xde, 0x93, 0x6d, 0x13, 0x05, 0x00, 0x00,
}
